/*
 For license information please see DicomJpeg2000.js.LICENSE.txt */
(self.aa=self.aa||[]).push([[794],{260:(Ea,fb,Pa)=>{Pa.d(fb,{h:()=>mb});const mb=function(){function Ya(){this.O=0}return Ya.prototype.Initialize=function(){return!0},Ya.prototype.yd=function(){},Ya}()},509:(Ea,fb,Pa)=>{function mb(){this.qj=new W}function Ya(Y){K.Uw>=K.Yl.Yw&&console.log("Warning: "+Y)}function Da(Y,Q,A){return Object.defineProperty(Y,Q,{value:A,enumerable:!0,configurable:!0,writable:!1}),A}function va(Y){for(var Q=1,A=0;Y>Q;)Q<<=1,A++;return A}function fa(Y,Q){return Y[Q]<<8|Y[Q+
1]}function la(Y,Q){return(Y[Q]<<24|Y[Q+1]<<16|Y[Q+2]<<8|Y[Q+3])>>>0}function T(){return new ca}Pa.r(fb);Pa.d(fb,{Mx:()=>ca,default:()=>T});var W=function(){function Y(){this.Jt=!1}function Q(ba,O,u){var B,E,V;ba=u.ax;var ha=u.gx,ia=1<<ba,ka=1<<ha,ma=O.Zc>>ba,ya=O.ud>>ha,Aa=O.ae+ia-1>>ba,Na=O.Oe+ka-1>>ha,Ha=O.Ei.Wc,sa=[],$a=[];for(B=ya;B<Na;B++)for(u=ma;u<Aa;u++)if((E={Rs:u,Ss:B,Zc:ia*u,ud:ka*B,ae:ia*(u+1),Oe:ka*(B+1)}).Ui=Math.max(O.Zc,E.Zc),E.Vi=Math.max(O.ud,E.ud),E.fp=Math.min(O.ae,E.ae),E.gp=
Math.min(O.Oe,E.Oe),V=Math.floor((E.Ui-O.Zc)/Ha.rv)+Math.floor((E.Vi-O.ud)/Ha.ov)*Ha.Nk,E.pv=V,E.Cw=O.type,E.Il=3,!(E.fp<=E.Ui||E.gp<=E.Vi)){sa.push(E);var La=$a[V];void 0!==La?(u<La.hg?La.hg=u:u>La.Tj&&(La.Tj=u),B<La.Vj?La.hg=B:B>La.Uj&&(La.Uj=B)):$a[V]=La={hg:u,Vj:B,Tj:u,Uj:B};E.yo=La}O.Xy={Yy:ba,Wy:ha,RA:Aa-ma+1,QA:Na-ya+1};O.ig=sa;O.lB=$a}function A(ba,O,u){var B=[];ba=ba.Qg;for(var E=0,V=ba.length;E<V;E++)for(var ha=ba[E].ig,ia=0,ka=ha.length;ia<ka;ia++){var ma=ha[ia];ma.pv===O&&B.push(ma)}return{Ku:u,
ig:B}}function M(ba){var O=ba.hc[ba.Ma.index],u=O.Be.yg,B=ba.Jb.Mc,E=0;for(ba=0;ba<B;ba++)E=Math.max(E,O.C[ba].cc.Fc);var V=0,ha=0,ia=0,ka=0;this.Fg=function(){for(;V<u;V++){for(;ha<=E;ha++){for(;ia<B;ia++){var ma=O.C[ia];if(!(ha>ma.cc.Fc)){ma=ma.Lc[ha];for(var ya=ma.Wc.ui;ka<ya;)return ma=A(ma,ka,V),ka++,ma;ka=0}}ia=0}ha=0}}}function y(ba){var O=ba.hc[ba.Ma.index],u=O.Be.yg,B=ba.Jb.Mc,E=0;for(ba=0;ba<B;ba++)E=Math.max(E,O.C[ba].cc.Fc);var V=0,ha=0,ia=0,ka=0;this.Fg=function(){for(;V<=E;V++){for(;ha<
u;ha++){for(;ia<B;ia++){var ma=O.C[ia];if(!(V>ma.cc.Fc)){ma=ma.Lc[V];for(var ya=ma.Wc.ui;ka<ya;)return ma=A(ma,ka,ha),ka++,ma;ka=0}}ia=0}ha=0}}}function na(ba){var O,u,B,E=ba.hc[ba.Ma.index],V=E.Be.yg,ha=ba.Jb.Mc,ia=0;for(B=0;B<ha;B++)ia=Math.max(ia,E.C[B].cc.Fc);var ka=new Int32Array(ia+1);for(u=0;u<=ia;++u){for(B=ba=0;B<ha;++B){var ma=E.C[B].Lc;u<ma.length&&(ba=Math.max(ba,ma[u].Wc.ui))}ka[u]=ba}var ya=B=u=O=0;this.Fg=function(){for(;u<=ia;u++){for(;ya<ka[u];ya++){for(;B<ha;B++){var Aa=E.C[B];if(!(u>
Aa.cc.Fc||(Aa=Aa.Lc[u],ya>=Aa.Wc.ui))){for(;O<V;)return Aa=A(Aa,ya,O),O++,Aa;O=0}}B=0}ya=0}}}function Ca(ba){var O=ba.hc[ba.Ma.index],u=O.Be.yg,B=ba.Jb.Mc,E=da(O),V=0,ha=0,ia=0,ka=0,ma=0;this.Fg=function(){for(;ma<E.Kk;ma++){for(;ka<E.Lk;ka++){for(;ia<B;ia++){for(var ya=O.C[ia],Aa=ya.cc.Fc;ha<=Aa;ha++){var Na=ya.Lc[ha],Ha=w(ka,ma,E.C[ia].Lc[ha],E,Na);if(null!==Ha){for(;V<u;)return ya=A(Na,Ha,V),V++,ya;V=0}}ha=0}ia=0}ka=0}}}function wa(ba){var O=ba.hc[ba.Ma.index],u=O.Be.yg,B=ba.Jb.Mc,E=da(O),V=0,
ha=0,ia=0,ka=0,ma=0;this.Fg=function(){for(;ia<B;++ia){for(var ya=O.C[ia],Aa=E.C[ia],Na=ya.cc.Fc;ma<Aa.Kk;ma++){for(;ka<Aa.Lk;ka++){for(;ha<=Na;ha++){var Ha=ya.Lc[ha],sa=w(ka,ma,Aa.Lc[ha],Aa,Ha);if(null!==sa){for(;V<u;)return ya=A(Ha,sa,V),V++,ya;V=0}}ha=0}ka=0}ma=0}}}function w(ba,O,u,B,E){ba*=B.minWidth;O*=B.minHeight;return 0!=ba%u.width||0!=O%u.height?null:ba/u.height+O/u.width*E.Wc.Nk}function da(ba){for(var O=ba.C.length,u=Number.MAX_VALUE,B=Number.MAX_VALUE,E=0,V=0,ha=Array(O),ia=0;ia<O;ia++){for(var ka=
ba.C[ia],ma=ka.cc.Fc,ya=Array(ma+1),Aa=Number.MAX_VALUE,Na=Number.MAX_VALUE,Ha=0,sa=0,$a=1;0<=ma;--ma){var La=ka.Lc[ma],Ra=$a*La.Wc.qv,eb=$a*La.Wc.nv;Aa=Math.min(Aa,Ra);Na=Math.min(Na,eb);Ha=Math.max(Ha,La.Wc.Nk);sa=Math.max(sa,La.Wc.fv);ya[ma]={width:Ra,height:eb};$a<<=1}u=Math.min(u,Aa);B=Math.min(B,Na);E=Math.max(E,Ha);V=Math.max(V,sa);ha[ia]={Lc:ya,minWidth:Aa,minHeight:Na,Lk:Ha,Kk:sa}}return{C:ha,minWidth:u,minHeight:B,Lk:E,Kk:V}}function ea(ba,O,u,B){function E(vb){for(;ma<vb;){if(u+ka>=O.length)throw Error("Unexpected EOF");
var Bb=O[u+ka];ka++;ya?(ia=ia<<7|Bb,ma+=7,ya=!1):(ia=ia<<8|Bb,ma+=8);255===Bb&&(ya=!0)}return ia>>>(ma-=vb)&(1<<vb)-1}function V(vb){if(255===O[u+ka-1]&&O[u+ka]===vb)ka+=1,vb=!0;else if(vb=255===O[u+ka]&&O[u+ka+1]===vb)ka+=2,vb=!0;return vb}function ha(){if(0===E(1))return 1;if(0===E(1))return 2;var vb=E(2);return 3>vb?vb+3:31>(vb=E(5))?vb+6:E(7)+37}var ia,ka=0,ma=0,ya=!1,Aa=ba.je.vw,Na=ba.je.Et;for(ba=ba.hc[ba.Ma.index].Hg;ka<B;)try{ma=0;ya&&(ka++,ya=!1);Aa&&V(145)&&(ka+=4);var Ha=ba.Fg();if(void 0===
Ha)return;if(E(1)){for(var sa,$a=Ha.Ku,La=[],Ra=0,eb=Ha.ig.length;Ra<eb;Ra++){var bb=(sa=Ha.ig[Ra]).yo,rb=sa.Rs-bb.hg,ob=sa.Ss-bb.Vj,db=!1,gb=!1;if(void 0!==sa.nu)db=!!E(1);else{if(void 0!==(bb=sa.yo).On)var pb=bb.On;else{var Fb=bb.Tj-bb.hg+1,kc=bb.Uj-bb.Vj+1;pb=new za(Fb,kc);var Qa=new xa(Fb,kc);bb.On=pb;bb.ix=Qa}for(pb.reset(rb,ob,$a);;){if(ka>=O.length)return;if(pb.xu())break;if(pb.yu())pb.ti();else if(E(1)){if(pb.hw(),pb.Au()){db=gb=sa.nu=!0;break}pb.ti()}else pb.zk()}}if(db){if(gb){for((Qa=bb.ix).reset(rb,
ob);;){if(ka>=O.length)return;if(E(1)){if(!Qa.ti())break}else Qa.zk()}sa.hx=Qa.value}for(var Pb=ha();E(1);)sa.Il++;var yc=va(Pb),Lc=E((Pb<1<<yc?yc-1:yc)+sa.Il);La.push({Vs:sa,Xj:Pb,Qm:Lc})}}ma=0;ya&&(ka++,ya=!1);for(Na&&V(146);0<La.length;){var hc=La.shift();void 0===(sa=hc.Vs).data&&(sa.data=[]);sa.data.push({data:O,start:u+ka,end:u+ka+hc.Qm,Xj:hc.Xj});ka+=hc.Qm}}}catch(vb){return}return ka}var R={Dx:0,Bx:1,tx:1,sx:2};Y.prototype={parse:function(ba){if(65359!==fa(ba,0))for(var O=0,u=ba.length;O<
u;){var B=8,E=la(ba,O),V=la(ba,O+4);if(O+=B,1===E&&(E=4294967296*la(ba,O)+la(ba,O+4),O+=8,B+=8),0===E&&(E=u-O+B),E<B)throw Error("JPX Error: Invalid box field size");B=E-B;E=!0;switch(V){case 1785737832:E=!1;break;case 1668246642:V=ba[O];if(ba[O+1],ba[O+2],1===V)switch(V=la(ba,O+3),V){case 16:case 17:case 18:break;default:Ya("Unknown colorspace "+V)}else 2===V&&(ha="ICC profile not supported",K.Uw>=K.Yl.ru&&console.log("Info: "+ha));break;case 1785737827:this.uo(ba,O,O+B);break;case 1783636E3:218793738!==
la(ba,O)&&Ya("Invalid JP2 signature");break;case 1783634458:case 1718909296:case 1920099697:case 1919251232:case 1768449138:break;default:Ya("Unsupported header type "+V+" ("+String.fromCharCode(V>>24&255,V>>16&255,V>>8&255,255&V)+")")}E&&(O+=B)}else this.uo(ba,0,ba.length);var ha},uo:function(ba,O,u){var B={};try{for(var E=!1,V=O;V+1<u;){var ha=fa(ba,V);V+=2;var ia,ka,ma,ya=0;switch(ha){case 65359:B.li=!0;break;case 65497:break;case 65361:ya=fa(ba,V);var Aa={};Aa.mh=la(ba,V+4);Aa.oh=la(ba,V+8);Aa.uj=
la(ba,V+12);Aa.xj=la(ba,V+16);Aa.wj=la(ba,V+20);Aa.zj=la(ba,V+24);Aa.vj=la(ba,V+28);Aa.yj=la(ba,V+32);var Na=fa(ba,V+36);Aa.Mc=Na;var Ha=[];var sa=V+38;for(var $a=0;$a<Na;$a++){var La={precision:1+(127&ba[sa]),Tn:!!(128&ba[sa]),lh:ba[sa+1],nh:ba[sa+1]},Ra=La,eb=Aa;Ra.$w=Math.ceil(eb.uj/Ra.lh);Ra.x1=Math.ceil(eb.mh/Ra.lh);Ra.ex=Math.ceil(eb.xj/Ra.nh);Ra.y1=Math.ceil(eb.oh/Ra.nh);Ra.width=Ra.x1-Ra.$w;Ra.height=Ra.y1-Ra.ex;Ha.push(La)}B.Jb=Aa;B.C=Ha;for(var bb=void 0,rb=B,ob=Ha,db=rb.Jb,gb=[],pb=Math.ceil((db.mh-
db.vj)/db.wj),Fb=Math.ceil((db.oh-db.yj)/db.zj),kc=0;kc<Fb;kc++)for(var Qa=0;Qa<pb;Qa++)(bb={}).lp=Math.max(db.vj+Qa*db.wj,db.uj),bb.np=Math.max(db.yj+kc*db.zj,db.xj),bb.mp=Math.min(db.vj+(Qa+1)*db.wj,db.mh),bb.op=Math.min(db.yj+(kc+1)*db.zj,db.oh),bb.width=bb.mp-bb.lp,bb.height=bb.op-bb.np,bb.C=[],gb.push(bb);rb.hc=gb;for(var Pb=0,yc=db.Mc;Pb<yc;Pb++)for(var Lc=ob[Pb],hc=0,vb=gb.length;hc<vb;hc++){var Bb={};bb=gb[hc];Bb.be=Math.ceil(bb.lp/Lc.lh);Bb.ce=Math.ceil(bb.np/Lc.nh);Bb.Hf=Math.ceil(bb.mp/
Lc.lh);Bb.If=Math.ceil(bb.op/Lc.nh);Bb.width=Bb.Hf-Bb.be;Bb.height=Bb.If-Bb.ce;bb.C[Pb]=Bb}B.pe=[];B.Mf=[];break;case 65372:ya=fa(ba,V);var Yb={};switch(sa=V+2,31&(ia=ba[sa++])){case 0:var Kb=8;var Rb=!0;break;case 1:Kb=16;Rb=!1;break;case 2:Kb=16;Rb=!0;break;default:throw Error("JPX Error: Invalid SQcd value "+ia);}Yb.cv=8===Kb;Yb.Po=Rb;Yb.En=ia>>5;for(ka=[];sa<ya+V;){var wb={};8===Kb?(wb.pg=ba[sa++]>>3,wb.Cg=0):(wb.pg=ba[sa]>>3,wb.Cg=(7&ba[sa])<<8|ba[sa+1],sa+=2);ka.push(wb)}Yb.Ul=ka;B.li?B.hh=
Yb:(B.Ma.hh=Yb,B.Ma.pe=[]);break;case 65373:ya=fa(ba,V);var ic,H={};switch(sa=V+2,257>B.Jb.Mc?ic=ba[sa++]:(ic=fa(ba,sa),sa+=2),31&(ia=ba[sa++])){case 0:Kb=8;Rb=!0;break;case 1:Kb=16;Rb=!1;break;case 2:Kb=16;Rb=!0;break;default:throw Error("JPX Error: Invalid SQcd value "+ia);}H.cv=8===Kb;H.Po=Rb;H.En=ia>>5;for(ka=[];sa<ya+V;)wb={},8===Kb?(wb.pg=ba[sa++]>>3,wb.Cg=0):(wb.pg=ba[sa]>>3,wb.Cg=(7&ba[sa])<<8|ba[sa+1],sa+=2),ka.push(wb);H.Ul=ka;B.li?B.pe[ic]=H:B.Ma.pe[ic]=H;break;case 65362:ya=fa(ba,V);var Z=
{};sa=V+2;var ja=ba[sa++];Z.an=!!(1&ja);Z.vw=!!(2&ja);Z.Et=!!(4&ja);Z.uv=ba[sa++];Z.yg=fa(ba,sa);sa+=2;Z.Wu=ba[sa++];Z.Fc=ba[sa++];Z.tp=2+(15&ba[sa++]);Z.up=2+(15&ba[sa++]);var ra=ba[sa++];if(Z.cw=!!(1&ra),Z.Hv=!!(2&ra),Z.Ew=!!(4&ra),Z.Ww=!!(8&ra),Z.sv=!!(16&ra),Z.Vv=!!(32&ra),Z.Mo=ba[sa++],Z.an){for(var Ja=[];sa<ya+V;){var Ua=ba[sa++];Ja.push({ne:15&Ua,oe:Ua>>4})}Z.zo=Ja}var Ta=[];if(Z.cw&&Ta.push("selectiveArithmeticCodingBypass"),Z.Hv&&Ta.push("resetContextProbabilities"),Z.Ew&&Ta.push("terminationOnEachCodingPass"),
Z.Ww&&Ta.push("verticalyStripe"),Z.sv&&Ta.push("predictableTermination"),0<Ta.length)throw E=!0,Error("JPX Error: Unsupported COD options ("+Ta.join(", ")+")");B.li?B.je=Z:(B.Ma.je=Z,B.Ma.Mf=[]);break;case 65424:ya=fa(ba,V);(ma={}).index=fa(ba,V+2);ma.length=la(ba,V+4);ma.Zj=ma.length+V-2;ma.vo=ba[V+8];ma.eB=ba[V+9];B.li=!1;0===ma.vo&&(ma.je=B.je,ma.Mf=B.Mf.slice(0),ma.hh=B.hh,ma.pe=B.pe.slice(0));B.Ma=ma;break;case 65427:if(0===(ma=B.Ma).vo){for(var Wa=B,Ib=Wa.Jb.Mc,xc=Wa.hc[ma.index],Jb=0;Jb<Ib;Jb++){var Wb=
xc.C[Jb];Wb.xv=void 0!==Wa.Ma.pe[Jb]?Wa.Ma.pe[Jb]:Wa.Ma.hh;Wb.cc=void 0!==Wa.Ma.Mf[Jb]?Wa.Ma.Mf[Jb]:Wa.Ma.je}xc.Be=Wa.Ma.je;for(var gc=B,jc=gc.hc[gc.Ma.index],fd=gc.Jb.Mc,Eb=0;Eb<fd;Eb++){for(var Za=jc.C[Eb],tb=Za.cc.Fc,Xb=[],ub=[],Va=0;Va<=tb;Va++){var ab,vd=Va,Zb=Za.cc,$b={};var zc=(Zb.an?($b.ne=Zb.zo[vd].ne,$b.oe=Zb.zo[vd].oe):($b.ne=15,$b.oe=15),$b.ax=0<vd?Math.min(Zb.tp,$b.ne-1):Math.min(Zb.tp,$b.ne),$b.gx=0<vd?Math.min(Zb.up,$b.oe-1):Math.min(Zb.up,$b.oe),$b);var sb={},Ac=1<<tb-Va;sb.jl=Math.ceil(Za.be/
Ac);sb.ll=Math.ceil(Za.ce/Ac);sb.kl=Math.ceil(Za.Hf/Ac);sb.ml=Math.ceil(Za.If/Ac);sb.Gv=Va;var Qd=1<<zc.ne,wd=1<<zc.oe,qe=0===sb.Gv,Rd=sb.kl>sb.jl?Math.ceil(sb.kl/Qd)-Math.floor(sb.jl/Qd):0,xd=sb.ml>sb.ll?Math.ceil(sb.ml/wd)-Math.floor(sb.ll/wd):0;sb.Wc={qv:Qd,nv:wd,Nk:Rd,fv:xd,ui:Rd*xd,rv:1<<zc.ne+(qe?0:-1),ov:1<<zc.oe+(qe?0:-1)};if(Xb.push(sb),0===Va)(ab={}).type="LL",ab.Zc=Math.ceil(Za.be/Ac),ab.ud=Math.ceil(Za.ce/Ac),ab.ae=Math.ceil(Za.Hf/Ac),ab.Oe=Math.ceil(Za.If/Ac),ab.Ei=sb,Q(0,ab,zc),ub.push(ab),
sb.Qg=[ab];else{var ac=1<<tb-Va+1,yd=[];(ab={}).type="HL";ab.Zc=Math.ceil(Za.be/ac-.5);ab.ud=Math.ceil(Za.ce/ac);ab.ae=Math.ceil(Za.Hf/ac-.5);ab.Oe=Math.ceil(Za.If/ac);ab.Ei=sb;Q(0,ab,zc);ub.push(ab);yd.push(ab);(ab={}).type="LH";ab.Zc=Math.ceil(Za.be/ac);ab.ud=Math.ceil(Za.ce/ac-.5);ab.ae=Math.ceil(Za.Hf/ac);ab.Oe=Math.ceil(Za.If/ac-.5);ab.Ei=sb;Q(0,ab,zc);ub.push(ab);yd.push(ab);(ab={}).type="HH";ab.Zc=Math.ceil(Za.be/ac-.5);ab.ud=Math.ceil(Za.ce/ac-.5);ab.ae=Math.ceil(Za.Hf/ac-.5);ab.Oe=Math.ceil(Za.If/
ac-.5);ab.Ei=sb;Q(0,ab,zc);ub.push(ab);yd.push(ab);sb.Qg=yd}}Za.Lc=Xb;Za.Qg=ub}var re=jc.Be.uv;switch(re){case 0:jc.Hg=new M(gc);break;case 1:jc.Hg=new y(gc);break;case 2:jc.Hg=new na(gc);break;case 3:jc.Hg=new Ca(gc);break;case 4:jc.Hg=new wa(gc);break;default:throw Error("JPX Error: Unsupported progression order "+re);}}ea(B,ba,V,ya=ma.Zj-V);break;case 65365:case 65367:case 65368:case 65380:ya=fa(ba,V);break;case 65363:throw Error("JPX Error: Codestream code 0xFF53 (COC) is not implemented");default:throw Error("JPX Error: Unknown codestream code: "+
ha.toString(16));}V+=ya}}catch(Ge){if(E||this.Jt)throw Ge;Ya("Trying to recover from "+Ge.message)}for(var Oc=B.C,tc=B.Jb.Mc,Pe=[],se=0,Qe=B.hc.length;se<Qe;se++){var Ab,Td=B.hc[se],uc=[];for(Ab=0;Ab<tc;Ab++){for(var te=uc,Se=Ab,Pc=Td.C[Ab],Ud=Pc.cc,Vd=Pc.xv,Ue=Ud.Fc,zd=Vd.Ul,Ad=Vd.Po,ue=Vd.En,Ve=Ud.Vv,We=B.C[Ab].precision,Wd=Ud.Mo,Xd=Wd?new Ga:new Sa,Bc=[],cb=0,hd=0;hd<=Ue;hd++){for(var id=Pc.Lc[hd],Yd=id.kl-id.jl,ve=id.ml-id.ll,Bd=new Float32Array(Yd*ve),Zd=0,we=id.Qg.length;Zd<we;Zd++){var jd,
pc;Ad?(jd=zd[cb].Cg,pc=zd[cb].pg,cb++):(jd=zd[0].Cg,pc=zd[0].pg+(0<hd?1-hd:0));for(var Cc=id.Qg[Zd],$d=R[Cc.type],xe=Bd,$c=Yd,Dc=Cc,Xe=Wd?1:Math.pow(2,We+$d-pc)*(1+jd/2048),kd=ue+pc-1,ye=Wd,Ye=Ve,$e=Dc.Zc,af=Dc.ud,Cd=Dc.ae-Dc.Zc,ze=Dc.ig,bf="H"===Dc.type.charAt(0)?1:0,cf="H"===Dc.type.charAt(1)?$c:0,Ub=0,Qc=ze.length;Ub<Qc;++Ub){var bc=ze[Ub],Ed=bc.fp-bc.Ui,md=bc.gp-bc.Vi;if(0!==Ed&&0!==md&&void 0!==bc.data){var Qb=new ua(Ed,md,bc.Cw,bc.hx,kd);var be=2;var ad,cc,bd=bc.data,Fd=0,Ae=0;var Nb=0;for(ad=
bd.length;Nb<ad;Nb++)Fd+=(cc=bd[Nb]).end-cc.start,Ae+=cc.Xj;var ce=new Int16Array(Fd),vc=0;Nb=0;for(ad=bd.length;Nb<ad;Nb++){var de=(cc=bd[Nb]).data.subarray(cc.start,cc.end);ce.set(de,vc);vc+=de.length}var ee=new U(ce,0,Fd);Qb.fw(ee);for(Nb=0;Nb<Ae;Nb++){switch(be){case 0:Qb.Mv();break;case 1:Qb.Lv();break;case 2:Qb.Kv(),Ye&&Qb.Ts()}be=(be+1)%3}var fe,Rc,Mc=bc.Ui-$e+(bc.Vi-af)*Cd,Od=Qb.Jh,Gf=Qb.jg,ef=Qb.Gh,ge=ye?0:.5;vc=0;var Tb="LL"!==Dc.type;for(Nb=0;Nb<md;Nb++){var Ce=2*(Mc/Cd|0)*($c-Cd)+bf+cf;
for(fe=0;fe<Ed;fe++){if(0!==(Rc=Gf[vc])){Rc=(Rc+ge)*Xe;0!==Od[vc]&&(Rc=-Rc);var Sc=ef[vc];xe[Tb?Ce+(Mc<<1):Mc]=ye&&Sc>=kd?Rc:Rc*(1<<kd-Sc)}Mc++;vc++}Mc+=Cd-Ed}}}}Bc.push({width:Yd,height:ve,items:Bd})}var lc=Xd.Ps(Bc,Pc.be,Pc.ce);te[Se]={left:Pc.be,top:Pc.ce,width:lc.width,height:lc.height,items:lc.items}}var jb=uc[0];var kb=Oc[0].Tn?new Int16Array(jb.items.length*tc):new Uint16Array(jb.items.length*tc);var dc,Hc,Gd,lb,mc,Yc,sc,Hf={left:jb.left,top:jb.top,width:jb.width,height:jb.height,items:kb},
xb=0;if(Td.Be.Wu){var Hd=4===tc,Ic=uc[0].items,Tc=uc[1].items,De=uc[2].items,gf=Hd?uc[3].items:null;var Uc=.5+(128<<(dc=Oc[0].precision-8));var he=-(Gd=.5*(Hc=255*(1<<dc)));var Ee=Td.C[0],Jd=tc-3;if(mc=Ic.length,Ee.cc.Mo)for(lb=0;lb<mc;lb++,xb+=Jd){var nd=Ic[lb]+Uc;var od=Tc[lb];var Vc=(sc=nd-((Yc=De[lb])+od>>2))+Yc;var wc=sc+od;kb[xb++]=0>=Vc?0:Vc>=Hc?255:Vc>>dc;kb[xb++]=0>=sc?0:sc>=Hc?255:sc>>dc;kb[xb++]=0>=wc?0:wc>=Hc?255:wc>>dc}else for(lb=0;lb<mc;lb++,xb+=Jd)nd=Ic[lb]+Uc,od=Tc[lb],Vc=nd+1.402*
(Yc=De[lb]),sc=nd-.34413*od-.71414*Yc,wc=nd+1.772*od,kb[xb++]=0>=Vc?0:Vc>=Hc?255:Vc>>dc,kb[xb++]=0>=sc?0:sc>=Hc?255:sc>>dc,kb[xb++]=0>=wc?0:wc>=Hc?255:wc>>dc;if(Hd)for(lb=0,xb=3;lb<mc;lb++,xb+=4){var ie=gf[lb];kb[xb]=ie<=he?0:ie>=Gd?255:ie+Uc>>dc}}else for(Ab=0;Ab<tc;Ab++)if(8===Oc[Ab].precision){var Jc=uc[Ab].items;Uc=.5+(128<<(dc=Oc[Ab].precision-8));he=-(Hc=127.5*(1<<dc));xb=Ab;lb=0;for(mc=Jc.length;lb<mc;lb++){var pd=Jc[lb];kb[xb]=pd<=he?0:pd>=Hc?255:pd+Uc>>dc;xb+=tc}}else{var Fe=Oc[Ab].Tn;if(Jc=
uc[Ab].items,Fe)for(xb=Ab,lb=0,mc=Jc.length;lb<mc;lb++)kb[xb]=Jc[lb],xb+=tc;else{Uc=.5+(128<<Oc[Ab].precision-8);var hf=Math.pow(2,Oc[Ab].precision)-1;xb=Ab;lb=0;for(mc=Jc.length;lb<mc;lb++)pd=Jc[lb],kb[xb]=Math.max(Math.min(pd+Uc,hf),0),xb+=tc}}Pe.push(Hf)}this.hc=Pe;this.width=B.Jb.mh-B.Jb.uj;this.height=B.Jb.oh-B.Jb.xj}};var xa=function(){function ba(O,u){var B=va(Math.max(O,u))+1;this.fb=[];for(var E=0;E<B;E++)this.fb.push({width:O,height:u,items:[]}),O=Math.ceil(O/2),u=Math.ceil(u/2)}return ba.prototype=
{reset:function(O,u){for(var B,E=0,V=0;E<this.fb.length;){var ha=O+u*(B=this.fb[E]).width;if(void 0!==B.items[ha]){V=B.items[ha];break}B.index=ha;O>>=1;u>>=1;E++}E--;(B=this.fb[E]).items[B.index]=V;this.mc=E;delete this.value},zk:function(){var O=this.fb[this.mc];O.items[O.index]++},ti:function(){var O=this.mc,u=this.fb[O],B=u.items[u.index];return 0>--O?(this.value=B,!1):(this.mc=O,(u=this.fb[O]).items[u.index]=B,!0)}},ba}(),za=function(){function ba(O,u){var B=va(Math.max(O,u))+1;this.fb=[];for(var E=
0;E<B;E++){for(var V=new Uint8Array(O*u),ha=new Uint8Array(O*u),ia=0,ka=V.length;ia<ka;ia++)V[ia]=0,ha[ia]=0;this.fb.push({width:O,height:u,items:V,status:ha});O=Math.ceil(O/2);u=Math.ceil(u/2)}}return ba.prototype={reset:function(O,u,B){this.lt=B;for(B=0;B<this.fb.length;){var E=this.fb[B];E.index=O+u*E.width;O>>=1;u>>=1;B++}this.mc=this.fb.length-1;this.minValue=this.fb[this.mc].items[0]},zk:function(){var O=this.fb[this.mc];O.items[O.index]+=1;O.items[O.index]>this.minValue&&(this.minValue=O.items[O.index])},
ti:function(){var O=this.mc;if(0>--O)return!1;this.mc=O;O=this.fb[O];return O.items[O.index]<this.minValue?O.items[O.index]=this.minValue:O.items[O.index]>this.minValue&&(this.minValue=O.items[O.index]),!0},Au:function(){return 0===this.mc},xu:function(){var O=this.fb[this.mc];return O.items[O.index]>this.lt},yu:function(){var O=this.fb[this.mc];return 0<O.status[O.index]},hw:function(){var O=this.fb[this.mc];O.status[O.index]=1}},ba}(),ua=function(){function ba(E,V,ha,ia,ka){this.width=E;this.height=
V;this.Km="HH"===ha?B:"HL"===ha?u:O;E*=V;this.si=new Uint8Array(E);this.Jh=new Uint8Array(E);this.jg=14<ka?new Uint32Array(E):6<ka?new Uint16Array(E):new Uint8Array(E);this.Sk=new Uint8Array(E);ka=new Uint8Array(E);if(0!==ia)for(V=0;V<E;V++)ka[V]=ia;this.Gh=ka;this.reset()}var O=new Uint8Array([0,5,8,0,3,7,8,0,4,7,8,0,0,0,0,0,1,6,8,0,3,7,8,0,4,7,8,0,0,0,0,0,2,6,8,0,3,7,8,0,4,7,8,0,0,0,0,0,2,6,8,0,3,7,8,0,4,7,8,0,0,0,0,0,2,6,8,0,3,7,8,0,4,7,8]),u=new Uint8Array([0,3,4,0,5,7,7,0,8,8,8,0,0,0,0,0,1,3,
4,0,6,7,7,0,8,8,8,0,0,0,0,0,2,3,4,0,6,7,7,0,8,8,8,0,0,0,0,0,2,3,4,0,6,7,7,0,8,8,8,0,0,0,0,0,2,3,4,0,6,7,7,0,8,8,8]),B=new Uint8Array([0,1,2,0,1,2,2,0,2,2,2,0,0,0,0,0,3,4,5,0,4,5,5,0,5,5,5,0,0,0,0,0,6,7,7,0,7,7,7,0,7,7,7,0,0,0,0,0,8,8,8,0,8,8,8,0,8,8,8,0,0,0,0,0,8,8,8,0,8,8,8,0,8,8,8]);return ba.prototype={fw:function(E){this.decoder=E},reset:function(){this.fd=new Int8Array(19);this.fd[0]=8;this.fd[17]=92;this.fd[18]=6},bl:function(E,V,ha){var ia,ka=this.si,ma=this.width,ya=this.height,Aa=0<V;V=V+
1<ma;0<E&&(ia=ha-ma,Aa&&(ka[ia-1]+=16),V&&(ka[ia+1]+=16),ka[ia]+=4);E+1<ya&&(ia=ha+ma,Aa&&(ka[ia-1]+=16),V&&(ka[ia+1]+=16),ka[ia]+=4);Aa&&(ka[ha-1]+=1);V&&(ka[ha+1]+=1);ka[ha]|=128},Mv:function(){for(var E=this.decoder,V=this.width,ha=this.height,ia=this.jg,ka=this.Jh,ma=this.si,ya=this.Sk,Aa=this.fd,Na=this.Km,Ha=this.Gh,sa=0;sa<ha;sa+=4)for(var $a=0;$a<V;$a++)for(var La=sa*V+$a,Ra=0;4>Ra;Ra++,La+=V){var eb=sa+Ra;if(eb>=ha)break;if(ya[La]&=-2,!ia[La]&&ma[La]){if(E.uc(Aa,Na[ma[La]])){var bb=this.ck(eb,
$a,La);ka[La]=bb;ia[La]=1;this.bl(eb,$a,La);ya[La]|=2}Ha[La]++;ya[La]|=1}}},ck:function(E,V,ha){var ia,ka,ma,ya,Aa,Na=this.width,Ha=this.height,sa=this.jg,$a=this.Jh;var La=0<V&&0!==sa[ha-1];V+1<Na&&0!==sa[ha+1]?(ma=$a[ha+1],ia=La?1-ma-(ka=$a[ha-1]):1-ma-ma):ia=La?1-(ka=$a[ha-1])-ka:0;V=3*ia;return La=0<E&&0!==sa[ha-Na],E+1<Ha&&0!==sa[ha+Na]?(ma=$a[ha+Na],ia=La?1-ma-$a[ha-Na]+V:1-ma-ma+V):ia=La?1-(ka=$a[ha-Na])-ka+V:V,0<=ia?(ya=9+ia,Aa=this.decoder.uc(this.fd,ya)):(ya=9-ia,Aa=1^this.decoder.uc(this.fd,
ya)),Aa},Lv:function(){for(var E,V=this.decoder,ha=this.width,ia=this.jg,ka=this.si,ma=this.fd,ya=this.Gh,Aa=this.Sk,Na=ha*this.height,Ha=4*ha,sa=0;sa<Na;sa=E){E=Math.min(Na,sa+Ha);for(var $a=0;$a<ha;$a++)for(var La=sa+$a;La<E;La+=ha)if(ia[La]&&0==(1&Aa[La])){var Ra=16;0!=(2&Aa[La])&&(Aa[La]^=2,Ra=0==(127&ka[La])?15:14);Ra=V.uc(ma,Ra);ia[La]=ia[La]<<1|Ra;ya[La]++;Aa[La]|=1}}},Kv:function(){for(var E,V=this.decoder,ha=this.width,ia=this.height,ka=this.si,ma=this.jg,ya=this.Jh,Aa=this.fd,Na=this.Km,
Ha=this.Gh,sa=this.Sk,$a=2*ha,La=3*ha,Ra=0;Ra<ia;Ra=E){E=Math.min(Ra+4,ia);for(var eb=Ra*ha,bb=Ra+3<ia,rb=0;rb<ha;rb++){var ob=eb+rb,db=0,gb=ob,pb=Ra;if(bb&&0===sa[ob]&&0===sa[ob+ha]&&0===sa[ob+$a]&&0===sa[ob+La]&&0===ka[ob]&&0===ka[ob+ha]&&0===ka[ob+$a]&&0===ka[ob+La]){if(!V.uc(Aa,18)){Ha[ob]++;Ha[ob+ha]++;Ha[ob+$a]++;Ha[ob+La]++;continue}0!=(db=V.uc(Aa,17)<<1|V.uc(Aa,17))&&(pb=Ra+db,gb+=db*ha);var Fb=this.ck(pb,rb,gb);ya[gb]=Fb;ma[gb]=1;this.bl(pb,rb,gb);sa[gb]|=2;gb=ob;for(ob=Ra;ob<=pb;ob++,gb+=
ha)Ha[gb]++;db++}for(pb=Ra+db;pb<E;pb++,gb+=ha)ma[gb]||0!=(1&sa[gb])||(1===V.uc(Aa,Na[ka[gb]])&&(Fb=this.ck(pb,rb,gb),ya[gb]=Fb,ma[gb]=1,this.bl(pb,rb,gb),sa[gb]|=2),Ha[gb]++)}}},Ts:function(){var E=this.decoder,V=this.fd;if(10!=(E.uc(V,17)<<3|E.uc(V,17)<<2|E.uc(V,17)<<1|E.uc(V,17)))throw Error("JPX Error: Invalid segmentation symbol");}},ba}(),Fa=function(){function ba(){}return ba.prototype.Ps=function(O,u,B){for(var E=O[0],V=1,ha=O.length;V<ha;V++)E=this.Fu(E,O[V],u,B);return E},ba.prototype.extend=
function(O,u,B){var E=u-1,V=u+1,ha=u+B-2;u+=B;O[E--]=O[V++];O[u++]=O[ha--];O[E--]=O[V++];O[u++]=O[ha--];O[E--]=O[V++];O[u++]=O[ha--];O[E]=O[V];O[u]=O[ha]},ba.prototype.Fu=function(O,u,B,E){var V,ha,ia,ka=O.width,ma=O.height,ya=O.items,Aa=u.width,Na=u.height;u=u.items;for(V=ia=0;V<ma;V++){var Ha=2*V*Aa;for(ha=0;ha<ka;ha++,ia++,Ha+=2)u[Ha]=ya[ia]}O.items=null;O=new Float32Array(Aa+8);if(1===Aa){if(0!=(1&B))for(ia=Ha=0;Ha<Na;Ha++,ia+=Aa)u[ia]*=.5}else for(ia=Ha=0;Ha<Na;Ha++,ia+=Aa)O.set(u.subarray(ia,
ia+Aa),4),this.extend(O,4,Aa),this.filter(O,4,Aa),u.set(O.subarray(4,4+Aa),ia);B=16;ka=[];for(V=0;V<B;V++)ka.push(new Float32Array(Na+8));V=0;if(O=4+Na,1===Na){if(0!=(1&E))for(E=0;E<Aa;E++)u[E]*=.5}else for(E=0;E<Aa;E++){if(0===V){B=Math.min(Aa-E,B);ia=E;for(Ha=4;Ha<O;ia+=Aa,Ha++)for(ma=0;ma<B;ma++)ka[ma][Ha]=u[ia+ma];V=B}ia=ka[--V];if(this.extend(ia,4,Na),this.filter(ia,4,Na),0===V)for(ia=E-B+1,Ha=4;Ha<O;ia+=Aa,Ha++)for(ma=0;ma<B;ma++)u[ia+ma]=ka[ma][Ha]}return{width:Aa,height:Na,items:u}},ba}(),
Sa=function(){function ba(){Fa.call(this)}return ba.prototype=Object.create(Fa.prototype),ba.prototype.filter=function(O,u,B){var E,V,ha=B>>1;B=(u|=0)-3;for(E=ha+4;E--;B+=2)O[B]*=.8128930661159609;var ia=.443506852043971*O[(B=u-2)-1];for(E=ha+3;E--&&(V=.443506852043971*O[B+1],O[B]=1.230174104914001*O[B]-ia-V,E--);B+=2)ia=.443506852043971*O[(B+=2)+1],O[B]=1.230174104914001*O[B]-ia-V;ia=.882911075530934*O[(B=u-1)-1];for(E=ha+2;E--&&(V=.882911075530934*O[B+1],O[B]-=ia+V,E--);B+=2)ia=.882911075530934*
O[(B+=2)+1],O[B]-=ia+V;ia=-.052980118572961*O[(B=u)-1];for(E=ha+1;E--&&(V=-.052980118572961*O[B+1],O[B]-=ia+V,E--);B+=2)ia=-.052980118572961*O[(B+=2)+1],O[B]-=ia+V;if(0!==ha)for(ia=-1.586134342059924*O[(B=u+1)-1],E=ha;E--&&(V=-1.586134342059924*O[B+1],O[B]-=ia+V,E--);B+=2)ia=-1.586134342059924*O[(B+=2)+1],O[B]-=ia+V},ba}(),Ga=function(){function ba(){Fa.call(this)}return ba.prototype=Object.create(Fa.prototype),ba.prototype.filter=function(O,u,B){var E,V=B>>1;B=u|=0;for(E=V+1;E--;B+=2)O[B]-=O[B-1]+
O[B+1]+2>>2;B=u+1;for(E=V;E--;B+=2)O[B]+=O[B-1]+O[B+1]>>1},ba}();return Y}(),U=function(){function Y(A,M,y){this.data=A;this.Sj=M;this.Zj=y;this.dd=A[M];this.ub=0;this.Gm();this.dd=this.dd<<7&65535|this.ub>>9&127;this.ub=this.ub<<7&65535;this.cf-=7;this.a=32768}var Q=[{N:22017,L:1,K:1,M:1},{N:13313,L:2,K:6,M:0},{N:6145,L:3,K:9,M:0},{N:2753,L:4,K:12,M:0},{N:1313,L:5,K:29,M:0},{N:545,L:38,K:33,M:0},{N:22017,L:7,K:6,M:1},{N:21505,L:8,K:14,M:0},{N:18433,L:9,K:14,M:0},{N:14337,L:10,K:14,M:0},{N:12289,
L:11,K:17,M:0},{N:9217,L:12,K:18,M:0},{N:7169,L:13,K:20,M:0},{N:5633,L:29,K:21,M:0},{N:22017,L:15,K:14,M:1},{N:21505,L:16,K:14,M:0},{N:20737,L:17,K:15,M:0},{N:18433,L:18,K:16,M:0},{N:14337,L:19,K:17,M:0},{N:13313,L:20,K:18,M:0},{N:12289,L:21,K:19,M:0},{N:10241,L:22,K:19,M:0},{N:9217,L:23,K:20,M:0},{N:8705,L:24,K:21,M:0},{N:7169,L:25,K:22,M:0},{N:6145,L:26,K:23,M:0},{N:5633,L:27,K:24,M:0},{N:5121,L:28,K:25,M:0},{N:4609,L:29,K:26,M:0},{N:4353,L:30,K:27,M:0},{N:2753,L:31,K:28,M:0},{N:2497,L:32,K:29,
M:0},{N:2209,L:33,K:30,M:0},{N:1313,L:34,K:31,M:0},{N:1089,L:35,K:32,M:0},{N:673,L:36,K:33,M:0},{N:545,L:37,K:34,M:0},{N:321,L:38,K:35,M:0},{N:273,L:39,K:36,M:0},{N:133,L:40,K:37,M:0},{N:73,L:41,K:38,M:0},{N:37,L:42,K:39,M:0},{N:21,L:43,K:40,M:0},{N:9,L:44,K:41,M:0},{N:5,L:45,K:42,M:0},{N:1,L:45,K:43,M:0},{N:22017,L:46,K:46,M:0}];return Y.prototype={Gm:function(){var A=this.data,M=this.Sj;255===A[M]?143<A[M+1]?(this.ub+=65280,this.cf=8):(M++,this.ub+=A[M]<<9,this.cf=7,this.Sj=M):(M++,this.ub+=M<this.Zj?
A[M]<<8:65280,this.cf=8,this.Sj=M);65535<this.ub&&(this.dd+=this.ub>>16,this.ub&=65535)},uc:function(A,M){var y,na=A[M]>>1,Ca=1&A[M],wa=Q[na],w=wa.N,da=this.a-w;if(this.dd<w)da<w?(da=w,y=Ca,na=wa.L):(da=w,y=1^Ca,1===wa.M&&(Ca=y),na=wa.K);else{if(this.dd-=w,0!=(32768&da))return this.a=da,Ca;da<w?(y=1^Ca,1===wa.M&&(Ca=y),na=wa.K):(y=Ca,na=wa.L)}do 0===this.cf&&this.Gm(),da<<=1,this.dd=this.dd<<1&65535|this.ub>>15&1,this.ub=this.ub<<1&65535,this.cf--;while(0==(32768&da));return this.a=da,A[M]=na<<1|
Ca,y}},Y}(),I="undefined"==typeof window?void 0:window,K={};I.vb||(I.vb={});I.vb.gB=!1;K.Yl={errors:0,Yw:1,ru:5};K.Hx={qz:1,pC:2,nC:3,oC:4,qC:5,XB:6,rC:7,fC:8,iC:9,save:10,restore:11,transform:12,moveTo:13,lineTo:14,hz:15,iz:16,jz:17,closePath:18,vB:19,stroke:20,Vy:21,fill:22,Iz:23,Mz:24,Jz:25,Uy:26,Ty:27,Fz:28,clip:29,Hz:30,Jy:31,Gz:32,TB:33,CC:34,jC:35,lC:36,gw:37,zC:38,AC:39,KA:40,mC:41,yC:42,MA:43,GC:44,FC:45,OA:46,NA:47,UB:48,VB:49,vC:50,cC:51,setStrokeColor:52,uC:53,setFillColor:54,bC:55,wC:56,
dC:57,xC:58,eC:59,tC:60,aC:61,DC:62,Gy:63,Fy:64,Dz:65,dB:66,IA:67,JA:68,Hy:69,Iy:70,Ez:71,Dy:72,Bz:73,TA:74,UA:75,Ey:76,Cz:77,Cy:78,Az:79,By:80,zz:81,bB:82,VA:83,WA:84,YA:85,$A:86,aB:87,ZA:88,XA:89,cB:90,$y:91};var x,m=K.Rx={Pw:"unknown",forms:"forms",DA:"javaScript",IC:"smask",EC:"shadingPattern",font:"font"},C=K.Ux=(x=[],{HA:function(Y){x.push(Y)},notify:function(Y){Ya('Unsupported feature "'+Y+'"');for(var Q=0,A=x.length;Q<A;Q++)x[Q](Y)}});K.BA=function(Y,Q){if(!Y)return!1;Y=/^[a-z][a-z0-9+\-.]*(?=:)/i.exec(Y);
if(!Y)return Q;switch(Y[0].toLowerCase()){case "http":case "https":case "ftp":case "mailto":case "tel":return!0;default:return!1}};K.uw=Da;K.Lx={Gx:1,vx:2};K.Kx=function(){function Y(Q,A){this.name="PasswordException";this.message=Q;this.code=A}return Y.prototype=Error(),Y.constructor=Y,Y}();K.Tx=function(){function Y(Q,A){this.name="UnknownErrorException";this.message=Q;this.details=A}return Y.prototype=Error(),Y.constructor=Y,Y}();K.xx=function(){function Y(Q){this.name="InvalidPDFException";this.message=
Q}return Y.prototype=Error(),Y.constructor=Y,Y}();K.Fx=function(){function Y(Q){this.name="MissingPDFException";this.message=Q}return Y.prototype=Error(),Y.constructor=Y,Y}();K.Sx=function(){function Y(Q,A){this.name="UnexpectedResponseException";this.message=Q;this.status=A}return Y.prototype=Error(),Y.constructor=Y,Y}();Object.defineProperty(K,"isLittleEndian",{configurable:!0,get:function(){return Da(K,"isLittleEndian",((Y=new Uint8Array(2))[0]=1,1===(new Uint16Array(Y.buffer))[0]));var Y}});Object.defineProperty(K,
"hasCanvasTypedArrays",{configurable:!0,get:function(){return Da(K,"hasCanvasTypedArrays",((Y=document.createElement("canvas")).width=Y.height=1,void 0!==Y.getContext("2d").createImageData(1,1).data.buffer));var Y}});Object.create(null);K.Vx=function(){function Y(){}return Y.transform=function(Q,A){return[Q[0]*A[0]+Q[2]*A[1],Q[1]*A[0]+Q[3]*A[1],Q[0]*A[2]+Q[2]*A[3],Q[1]*A[2]+Q[3]*A[3],Q[0]*A[4]+Q[2]*A[5]+Q[4],Q[1]*A[4]+Q[3]*A[5]+Q[5]]},Y.sign=function(Q){return 0>Q?-1:1},Y.inherit=function(Q,A,M){for(var y in Q.prototype=
Object.create(A.prototype),Q.prototype.constructor=Q,M)Q.prototype[y]=M[y]},Y}();K.Jx=function(){function Y(Q,A,M,y,na,Ca){this.viewBox=Q;this.scale=A;this.rotation=M;this.offsetX=y;this.offsetY=na;var wa,w,da,ea,R,xa=(Q[2]+Q[0])/2,za=(Q[3]+Q[1])/2;switch(0>(M%=360)?M+360:M){case 180:M=-1;var ua=wa=0;var Fa=1;break;case 90:M=0;ua=wa=1;Fa=0;break;case 270:M=0;ua=wa=-1;Fa=0;break;default:M=1,ua=wa=0,Fa=-1}Ca&&(ua=-ua,Fa=-Fa);0===M?(w=Math.abs(za-Q[1])*A+y,da=Math.abs(xa-Q[0])*A+na,ea=Math.abs(Q[3]-
Q[1])*A,R=Math.abs(Q[2]-Q[0])*A):(w=Math.abs(xa-Q[0])*A+y,da=Math.abs(za-Q[1])*A+na,ea=Math.abs(Q[2]-Q[0])*A,R=Math.abs(Q[3]-Q[1])*A);this.transform=[M*A,wa*A,ua*A,Fa*A,w-M*A*xa-ua*A*za,da-wa*A*xa-Fa*A*za];this.width=ea;this.height=R}return Y.prototype={clone:function(Q){var A="scale"in(Q=Q||{})?Q.scale:this.scale;return new Y(this.viewBox.slice(),A,"rotation"in Q?Q.rotation:this.rotation,this.offsetX,this.offsetY,Q.vz)}},Y}();K.gz=function(){var Y={};return Y.promise=new Promise(function(Q,A){Y.resolve=
Q;Y.reject=A}),Y};(function(){function Y(A){this.Nd=0;this.$f=[];try{A.call(this,this.es.bind(this),this.tm.bind(this))}catch(M){this.tm(M)}}if(I.Promise)return"function"!=typeof I.Promise.all&&(I.Promise.all=function(A){var M,y,na=0,Ca=[],wa=new I.Promise(function(w,da){M=w;y=da});return A.forEach(function(w,da){na++;w.then(function(ea){Ca[da]=ea;0==--na&&M(Ca)},y)}),0===na&&M(Ca),wa}),"function"!=typeof I.Promise.resolve&&(I.Promise.resolve=function(A){return new I.Promise(function(M){M(A)})}),
"function"!=typeof I.Promise.reject&&(I.Promise.reject=function(A){return new I.Promise(function(M,y){y(A)})}),void("function"!=typeof I.Promise.prototype.catch&&(I.Promise.prototype.catch=function(A){return I.Promise.prototype.then(void 0,A)}));var Q={handlers:[],Xk:!1,vd:[],Qk:!1,Uo:function(A){0!==A.Nd&&(this.handlers=this.handlers.concat(A.$f),A.$f=[],this.Xk||(this.Xk=!0,setTimeout(this.No.bind(this),0)))},No:function(){for(var A=Date.now()+1;0<this.handlers.length;){var M=this.handlers.shift(),
y=M.Wi.Nd,na=M.Wi.Dc;try{1===y?"function"==typeof M.no&&(na=M.no(na)):"function"==typeof M.mo&&(na=M.mo(na),y=1,M.Wi.Lj&&this.Ev(M.Wi))}catch(Ca){y=2,na=Ca}if(M.av.fg(y,na),Date.now()>=A)break}0<this.handlers.length?setTimeout(this.No.bind(this),0):this.Xk=!1},Cs:function(A){this.vd.push({promise:A,time:Date.now()});this.Vo()},Ev:function(A){A.Lj=!1;for(var M=0;M<this.vd.length;M++)this.vd[M].promise===A&&(this.vd.splice(M),M--)},Vo:function(){this.Qk||(this.Qk=!0,setTimeout(function(){this.Qk=!1;
for(var A=Date.now(),M=0;M<this.vd.length;M++)if(500<A-this.vd[M].time){var y=this.vd[M].promise.Dc,na="Unhandled rejection: "+y;y.stack&&(na+="\n"+y.stack);Ya(na);this.vd.splice(M);M--}this.vd.length&&this.Vo()}.bind(this),500))}};Y.all=function(A){function M(za){2!==Ca.Nd&&(w=[],na(za))}var y,na,Ca=new Y(function(za,ua){y=za;na=ua}),wa=A.length,w=[];if(0===wa)return y(w),Ca;for(var da=0,ea=A.length;da<ea;++da){var R=A[da],xa=function(za){return function(ua){2!==Ca.Nd&&(w[za]=ua,0==--wa&&y(w))}}(da);
Y.Sn(R)?R.then(xa,M):xa(R)}return Ca};Y.Sn=function(A){return A&&"function"==typeof A.then};Y.resolve=function(A){return new Y(function(M){M(A)})};Y.reject=function(A){return new Y(function(M,y){y(A)})};Y.prototype={Nd:null,Dc:null,$f:null,Lj:null,fg:function(A,M){1!==this.Nd&&2!==this.Nd&&(1===A&&Y.Sn(M)?M.then(this.fg.bind(this,1),this.fg.bind(this,2)):(this.Nd=A,this.Dc=M,2===A&&0===this.$f.length&&(this.Lj=!0,Q.Cs(this)),Q.Uo(this)))},es:function(A){this.fg(1,A)},tm:function(A){this.fg(2,A)},
then:function(A,M){var y=new Y(function(na,Ca){this.resolve=na;this.reject=Ca});return this.$f.push({Wi:this,no:A,mo:M,av:y}),Q.Uo(this),y},catch:function(A){return this.then(void 0,A)}};I.Promise=Y})();K.Zs=function(Y,Q){if("undefined"!=typeof Blob)return new Blob([Y],{type:Q});!function(A){if(1<arguments.length){var M=["Error:"];M.push.apply(M,arguments);console.log.apply(console,M);A=[].join.call(arguments," ")}else console.log("Error: "+A);try{throw Error();}catch(y){M=y.stack?y.stack.split("\n").slice(2).join("\n"):
""}throw console.log(M),C.notify(m.Pw),Error(A);}("Blob type not recognized: ")};K.createObjectURL=function(Y,Q){if(!K.rz&&"undefined"!=typeof URL&&URL.createObjectURL)return Y=K.Zs(Y,Q),URL.createObjectURL(Y);Q="data:"+Q+";base64,";for(var A=0,M=Y.length;A<M;A+=3){var y=255&Y[A],na=255&Y[A+1],Ca=255&Y[A+2];Q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/="[y>>2]+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/="[(3&y)<<4|na>>4]+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/="[A+
1<M?(15&na)<<2|Ca>>6:64]+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/="[A+2<M?63&Ca:64]}return Q};var D,p=Pa(12),z=Pa(608),G=Pa(369);Ea=Pa(260);var L=(D=function(Y,Q){return D=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(A,M){A.__proto__=M}||function(A,M){for(var y in M)Object.prototype.hasOwnProperty.call(M,y)&&(A[y]=M[y])},D(Y,Q)},function(Y,Q){function A(){this.constructor=Y}if("function"!=typeof Q&&null!==Q)throw new TypeError("Class extends value "+String(Q)+
" is not a constructor or null");D(Y,Q);Y.prototype=null===Q?Object.create(Q):(A.prototype=Q.prototype,new A)}),ca=function(Y){function Q(){return null!==Y&&Y.apply(this,arguments)||this}return L(Q,Y),Q.prototype.yc=function(A,M,y,na){A=p.h.Nc(y,A,na);A=Q.De(A);return new G.h(A,z.h.Oc())},Q.prototype.zd=function(A,M,y,na){A=p.h.Nc(y,A,na);return new G.h(A,z.h.Of())},Q.De=function(A){var M=new mb;A=new Uint8Array(A.buffer,A.byteOffset,A.byteLength);M.qj.parse(A);A=M.qj.hc.length;if(1!=A)throw"JPEG2000 decoder returned a tileCount of "+
A+", when 1 is expected";return new DataView(M.qj.hc[0].items.buffer)},Q}(Ea.h)}}]);
