(self.aa=self.aa||[]).push([[205],{209:(Ea,fb,Pa)=>{function mb(){this.To=this.Rm=this.Am=0}function Ya(){this.rp=this.Eo=this.Gn=0}function Da(){return new C}Pa.r(fb);Pa.d(fb,{nx:()=>C,default:()=>Da});var va=function(){function D(p){this.buffer=p;this.index=0}return D.prototype.eb=function(){var p=this.buffer.getUint16(this.index,!1);return this.index+=2,p},D.prototype.ta=function(){var p=this.buffer.getUint8(this.index);return this.index+=1,p},D}(),fa=function(){function D(){}return D.Rc=function(p){for(var z=
1;z<arguments.length;z++);z=Array(p||0);var G=p;if(1<arguments.length)for(var L=Array.prototype.slice.call(arguments,1);G--;)z[p-1-G]=D.Rc.apply(this,L);return z},D}(),la=function(){function D(){this.xg=fa.Rc(4,2,16);this.Rg=[];this.fe=fa.Rc(4,2,16,200);this.$c=fa.Rc(4,2);this.$c[0][0]=0;this.$c[1][0]=0;this.$c[2][0]=0;this.$c[3][0]=0;this.$c[0][1]=0;this.$c[1][1]=0;this.$c[2][1]=0;this.$c[3][1]=0;this.Rg[0]=0;this.Rg[1]=0;this.Rg[2]=0;this.Rg[3]=0}return D.prototype.read=function(p,z){var G,L,ca,
Y,Q=0,A=p.eb();for(Q+=2;Q<A;){if(Q+=1,3<(L=15&(G=p.ta())))throw Error("ERROR: Huffman table ID > 3");if(2<(G>>=4))throw Error("ERROR: Huffman table [Table class > 2 ]");this.Rg[L]=1;this.$c[L][G]=1;for(ca=0;16>ca;ca+=1)this.xg[L][G][ca]=p.ta(),Q+=1;for(ca=0;16>ca;ca+=1)for(Y=0;Y<this.xg[L][G][ca];Y+=1){if(Q>A)throw Error("ERROR: Huffman table format error [count>Lh]");this.fe[L][G][ca][Y]=p.ta();Q+=1}}if(Q!==A)throw Error("ERROR: Huffman table format error [count!=Lf]");for(ca=0;4>ca;ca+=1)for(Y=
0;2>Y;Y+=1)0!==this.$c[ca][Y]&&this.Ls(z[ca][Y],this.xg[ca][Y],this.fe[ca][Y]);return 1},D.prototype.Ls=function(p,z,G){var L,ca,Y,Q=0;for(L=0;8>L;L+=1)for(ca=0;ca<z[L];ca+=1)for(Y=0;Y<256>>L+1;Y+=1)p[Q]=G[L][ca]|L+1<<8,Q+=1;for(L=1;256>Q;L+=1,Q+=1)p[Q]=L|D.tj;var A=1;Q=0;for(L=8;16>L;L+=1)for(ca=0;ca<z[L];ca+=1){for(Y=0;Y<256>>L-7;Y+=1)p[256*A+Q]=G[L][ca]|L+1<<8,Q+=1;if(256<=Q){if(256<Q)throw Error("ERROR: Huffman table error(1)!");Q=0;A+=1}}},D.tj=2147483648,D}(),T=function(){function D(){this.precision=
[];this.Df=fa.Rc(4,64);this.Sg=[];this.Sg[0]=0;this.Sg[1]=0;this.Sg[2]=0;this.Sg[3]=0}return D.Dt=function(p,z){var G;for(G=0;8>G;G+=1)p[z[G]]*=90,p[z[32+G]]*=90,p[z[16+G]]*=118,p[z[48+G]]*=49,p[z[40+G]]*=71,p[z[8+G]]*=126,p[z[56+G]]*=25,p[z[24+G]]*=106;for(G=0;8>G;G+=1)p[z[8*G]]*=90,p[z[4+8*G]]*=90,p[z[2+8*G]]*=118,p[z[6+8*G]]*=49,p[z[5+8*G]]*=71,p[z[1+8*G]]*=126,p[z[7+8*G]]*=25,p[z[3+8*G]]*=106;for(G=0;64>G;G+=1)p[G]>>=6},D.prototype.read=function(p,z){var G,L,ca=0,Y=p.eb();for(ca+=2;ca<Y;){if(ca+=
1,3<(L=15&(G=p.ta())))throw Error("ERROR: Quantization table ID > 3");if(this.precision[L]=G>>4,0===this.precision[L])this.precision[L]=8;else{if(1!==this.precision[L])throw Error("ERROR: Quantization table precision error");this.precision[L]=16}if(this.Sg[L]=1,8===this.precision[L])for(G=0;64>G;G+=1){if(ca>Y)throw Error("ERROR: Quantization table format error");this.Df[L][G]=p.ta();ca+=1}else for(G=0;64>G;G+=1){if(ca>Y)throw Error("ERROR: Quantization table format error");this.Df[L][G]=p.eb();ca+=
2}D.Dt(this.Df[L],z)}if(ca!==Y)throw Error("ERROR: Quantization table error [count!=Lq]");return 1},D}(),W=function(){function D(){this.C=[];this.precision=this.Eb=this.Vm=this.Um=0}return D.prototype.read=function(p){var z,G,L=0,ca=p.eb();L+=2;this.precision=p.ta();L+=1;this.Vm=p.eb();L+=2;this.Um=p.eb();L+=2;this.Eb=p.ta();L+=1;for(z=1;z<=this.Eb;z+=1){if(L>ca)throw Error("ERROR: frame format error");if(G=p.ta(),(L+=1)>=ca)throw Error("ERROR: frame format error [c>=Lf]");var Y=p.ta();L+=1;this.C[G]||
(this.C[G]=new Ya);this.C[G].Gn=Y>>4;this.C[G].rp=15&Y;this.C[G].Eo=p.ta();L+=1}if(L!==ca)throw Error("ERROR: frame format error [Lf!=count]");return 1},D}(),U=function(){function D(){this.selection=this.Eb=0;this.C=[]}return D.prototype.read=function(p){var z,G=0,L=p.eb();G+=2;this.Eb=p.ta();G+=1;for(z=0;z<this.Eb;z+=1){if(this.C[z]=new mb,G>L)throw Error("ERROR: scan header format error");this.C[z].To=p.ta();G+=1;var ca=p.ta();G+=1;this.C[z].Rm=ca>>4;this.C[z].Am=15&ca}if(this.selection=p.ta(),
G+=1,p.ta(),G+=1,p.ta(),G+1!==L)throw Error("ERROR: scan header format error [count!=Ns]");return 1},D}(),I=function(){function D(){this.ke=[];this.ri=[];this.Me=this.Xa=this.Ga=this.ie=this.Hb=this.selection=this.Mg=this.Eb=this.ob=this.Cb=0;this.td=null;this.Fi=!1;this.sf=0;this.hv=function(p){var z=this.Xa*this.Hb+this.Ga;this.Ga<this.Hb&&this.Xa<this.ie&&(this.Ef(z,p[0],0),this.Ef(z,p[1],1),this.Ef(z,p[2],2),this.Ga+=1,this.Ga>=this.Hb&&(this.Xa+=1,this.Ga=0))};this.Vk=function(){if(4!==this.stream.eb())throw Error("ERROR: Define number format throw new IOException [Ld!=4]");
return this.stream.eb()};this.frame=new W;this.Jn=new la;this.Tk=new T;this.Ki=new U;fa.Rc(10,4,64);this.$g=fa.Rc(4,2,12800);this.ke=[];this.ri=[];this.zm=fa.Rc(10,1);this.$j=fa.Rc(10,1);this.Do=fa.Rc(10,1);this.Me=this.Xa=this.Ga=this.ie=this.Hb=this.selection=this.Mg=this.Eb=this.ob=this.Cb=0;this.td=null;this.Fi=!1;this.sf=0}return D.prototype.Io=function(){var p=0,z=this.stream.eb();for(p+=2;p<z;)this.stream.ta(),p+=1;return z},D.prototype.Jo=function(){var p="",z=0,G=this.stream.eb();for(z+=
2;z<G;)p+=this.stream.ta(),z+=1;return p},D.prototype.gu=function(p,z){return this.td.getUint8(3*p+z)},D.prototype.tw=function(p,z,G){this.td.setUint8(3*p+G,z)},D.prototype.fu=function(p){return this.td.getInt8(p)&this.sf},D.prototype.sw=function(p,z){this.td.setInt8(p,z)},D.prototype.so=function(p){this.Ga<this.Hb&&this.Xa<this.ie&&(this.Ef(this.Xa*this.Hb+this.Ga,this.sf&p[0]),this.Ga+=1,this.Ga>=this.Hb&&(this.Xa+=1,this.Ga=0))},D.prototype.eu=function(p){return this.td.getInt16(2*p,!0)&this.sf},
D.prototype.rw=function(p,z){this.td.setInt16(2*p,z,!0)},D.prototype.Wv=function(p){return this.gf(p)},D.prototype.Xv=function(p){return this.Ie(p)},D.prototype.Yv=function(p){return this.ai(p)},D.prototype.Zv=function(p){return this.gf(p)+this.Ie(p)-this.ai(p)},D.prototype.$v=function(p){return this.gf(p)+(this.Ie(p)-this.ai(p)>>1)},D.prototype.aw=function(p){return this.Ie(p)+(this.gf(p)-this.ai(p)>>1)},D.prototype.bw=function(p){return(this.gf(p)+this.Ie(p))/2},D.prototype.gf=function(p){return 0<
this.Ga?this.vg(this.Xa*this.Hb+this.Ga-1,p):0<this.Xa?this.Ie(p):1<<this.frame.precision-1},D.prototype.Ie=function(p){return 0<this.Xa?this.vg((this.Xa-1)*this.Hb+this.Ga,p):this.gf(p)},D.prototype.ai=function(p){return 0<this.Ga&&0<this.Xa?this.vg((this.Xa-1)*this.Hb+this.Ga-1,p):this.Ie(p)},D.prototype.dk=function(p,z,G){return 1==this.Eb?this.qt(p,z,G):3==this.Eb?this.ot(p,z,G):-1},D.prototype.qt=function(p,z,G){var L,ca,Y;this.Fi?(this.Fi=!1,p[0]=1<<this.frame.precision-1):p[0]=this.Yc();for(ca=
0;ca<this.ri[0];ca+=1){if(65280<=(L=this.nk(this.$j[0],z,G)))return L;if((Y=(L=this.rk(p,L,z,G))>>8)>=D.Rl&&Y<=D.Sl)return Y;p[0]+=L}return 0},D.prototype.nk=function(p,z,G){var L,ca;if(8>G[0]?(z[0]<<=8,255===(ca=this.stream.ta())&&(this.Cb=this.stream.ta(),0!==this.Cb&&(this.ob=9)),z[0]|=ca):G[0]-=8,0!=((L=p[z[0]>>G[0]])&D.tj)){if(0!==this.ob)return this.ob=0,65280|this.Cb;z[0]&=65535>>16-G[0];z[0]<<=8;255===(ca=this.stream.ta())&&(this.Cb=this.stream.ta(),0!==this.Cb&&(this.ob=9));z[0]|=ca;L=p[256*
(255&L)+(z[0]>>G[0])];G[0]+=8}if(G[0]+=8-(L>>8),0>G[0])throw Error("index="+G[0]+" temp="+z[0]+" code="+L+" in HuffmanValue()");return G[0]<this.ob?(this.ob=0,65280|this.Cb):(z[0]&=65535>>16-G[0],255&L)},D.prototype.rk=function(p,z,G,L){var ca;if(0===z)return 0;if(16===z)return 0<=p[0]?-32768:32768;if(L[0]-=z,0<=L[0]){if(L[0]<this.ob&&!this.zu())return this.ob=0,(65280|this.Cb)<<8}else{if(G[0]<<=8,255===(ca=this.stream.ta())&&(this.Cb=this.stream.ta(),0!==this.Cb&&(this.ob=9)),G[0]|=ca,L[0]+=8,0>
L[0]){if(0!==this.ob)return this.ob=0,(65280|this.Cb)<<8;G[0]<<=8;255===(ca=this.stream.ta())&&(this.Cb=this.stream.ta(),0!==this.Cb&&(this.ob=9));G[0]|=ca;L[0]+=8}if(0>L[0])throw Error("index="+L[0]+" in getn()");if(L[0]<this.ob)return this.ob=0,(65280|this.Cb)<<8}p=G[0]>>L[0];G[0]&=65535>>16-L[0];return p<1<<z-1&&(p+=1+(-1<<z)),p},D.prototype.ot=function(p,z,G){var L,ca,Y,Q;p[0]=this.Yc(0);p[1]=this.Yc(1);p[2]=this.Yc(2);for(ca=0;ca<this.Eb;ca+=1){var A=this.Do[ca];var M=this.zm[ca];var y=this.$j[ca];
for(Y=0;Y<this.ri[ca];Y+=1){for(L=0;L<this.ke.length;L+=1)this.ke[L]=0;if(65280<=(L=this.nk(y,z,G)))return L;p[ca]=this.ke[0]=p[ca]+this.rk(G,L,z,G);this.ke[0]*=A[0];for(Q=1;64>Q;Q+=1){if(65280<=(L=this.nk(M,z,G)))return L;if(Q+=L>>4,0==(15&L)){if(0==L>>4)break}else this.ke[D.br[Q]]=this.rk(G,15&L,z,G)*A[Q]}}}return 0},D.prototype.zu=function(){return this.Ga===this.Hb-1&&this.Xa===this.ie-1},D.prototype.decode=function(p,z){var G=0,L=[],ca=[],Y=[];if(void 0!==z&&(this.Me=z),this.stream=new va(p),
this.Ga=0,this.Xa=0,65496!==this.stream.eb())throw Error("Not a JPEG file");for(p=this.stream.eb();4092!=p>>4||65476===p;){switch(p){case 65476:this.Jn.read(this.stream,this.$g);break;case 65484:throw Error("Program doesn't support arithmetic coding. (format throw new IOException)");case 65499:this.Tk.read(this.stream,D.Wl);break;case 65501:this.Mg=this.Vk();break;case 65504:case 65505:case 65506:case 65507:case 65508:case 65509:case 65510:case 65511:case 65512:case 65513:case 65514:case 65515:case 65516:case 65517:case 65518:case 65519:this.Io();
break;case 65534:this.Jo();break;default:if(255!=p>>8)throw Error("ERROR: format throw new IOException! (decode)");}p=this.stream.eb()}if(65472>p||65479<p)throw Error("ERROR: could not handle arithmetic code!");this.frame.read(this.stream);p=this.stream.eb();do{for(;65498!==p;){switch(p){case 65476:this.Jn.read(this.stream,this.$g);break;case 65484:throw Error("Program doesn't support arithmetic coding. (format throw new IOException)");case 65499:this.Tk.read(this.stream,D.Wl);break;case 65501:this.Mg=
this.Vk();break;case 65504:case 65505:case 65506:case 65507:case 65508:case 65509:case 65510:case 65511:case 65512:case 65513:case 65514:case 65515:case 65516:case 65517:case 65518:case 65519:this.Io();break;case 65534:this.Jo();break;default:if(255!=p>>8)throw Error("ERROR: format throw new IOException! (Parser.decode)");}p=this.stream.eb()}switch(this.precision=this.frame.precision,this.C=this.frame.C,this.Me||(this.Me=Math.ceil(this.precision/8)),1==this.Me?this.sf=255:this.sf=65535,this.Ki.read(this.stream),
this.Eb=this.Ki.Eb,this.selection=this.Ki.selection,1===this.Me?3===this.Eb?(this.vg=this.gu,this.Ef=this.tw,this.ya=this.hv):(this.vg=this.fu,this.Ef=this.sw,this.ya=this.so):(this.vg=this.eu,this.Ef=this.rw,this.ya=this.so),this.selection){case 2:this.Yc=this.Xv;break;case 3:this.Yc=this.Yv;break;case 4:this.Yc=this.Zv;break;case 5:this.Yc=this.$v;break;case 6:this.Yc=this.aw;break;case 7:this.Yc=this.bw;break;default:this.Yc=this.Wv}this.$k=this.Ki.C;this.Df=this.Tk.Df;for(z=0;z<this.Eb;z+=1){var Q=
this.$k[z].To;this.Do[z]=this.Df[this.C[Q].Eo];this.ri[z]=this.C[Q].rp*this.C[Q].Gn;this.$j[z]=this.$g[this.$k[z].Rm][0];this.zm[z]=this.$g[this.$k[z].Am][1]}this.Hb=this.frame.Um;this.ie=this.frame.Vm;this.td=new DataView(new ArrayBuffer(this.Hb*this.ie*this.Me*this.Eb));for(G+=1;;){ca[0]=0;for(z=Y[0]=0;10>z;z+=1)L[z]=1<<this.precision-1;if(0===this.Mg){for(p=this.dk(L,ca,Y);0===p&&this.Ga<this.Hb&&this.Xa<this.ie;)this.ya(L),p=this.dk(L,ca,Y);break}for(z=0;z<this.Mg&&(this.Fi=0==z,p=this.dk(L,ca,
Y),this.ya(L),0===p);z+=1);if(0===p&&(0!==this.ob?(p=65280|this.Cb,this.ob=0):p=this.stream.eb()),!(p>=D.Rl&&p<=D.Sl))break}65500===p&&1===G&&(this.Vk(),p=this.stream.eb())}while(65497!==p&&this.Ga<this.Hb&&this.Xa<this.ie&&0===G);return this.td},D.br=[0,5,40,16,45,2,7,42,21,56,8,61,18,47,1,4,41,23,58,13,32,24,37,10,63,17,44,3,6,43,20,57,15,34,29,48,53,26,39,9,60,19,46,22,59,12,33,31,50,55,25,36,11,62,14,35,28,49,52,27,38,30,51,54],D.Wl=[0,1,5,6,14,15,27,28,2,4,7,13,16,26,29,42,3,8,12,17,25,30,41,
43,9,11,18,24,31,40,44,53,10,19,23,32,39,45,52,54,20,22,33,38,46,51,55,60,21,34,37,47,50,56,59,61,35,36,48,49,57,58,62,63],D.tj=2147483648,D.Rl=65488,D.Sl=65495,D}(),K=Pa(12),x=Pa(608),m=Pa(369),C=function(){function D(){this.O=0}return D.prototype.Initialize=function(){return!0},D.prototype.yc=function(p,z,G,L){p=K.h.Nc(G,p,L);p=(new I).decode(p);return new m.h(p,x.h.Oc())},D.prototype.zd=function(p,z,G,L){p=K.h.Nc(G,p,L);return new m.h(p,x.h.kj())},D.prototype.yd=function(){},D}()}}]);
