name: Setup
description: Setup the environment

inputs:
  node-version:
    description: The version of node.js
    required: false
    default: '20'

runs:
  using: composite
  steps:
    - name: Set environment variables
      shell: bash
      run: |
        echo "FORCE_COLOR=1" >> "${GITHUB_ENV}"
        echo "DO_NOT_TRACK=1" >> "${GITHUB_ENV}"

    - name: Enable corepack
      run: corepack enable
      shell: bash

    - name: Install pnpm
      run: pnpm --version
      shell: bash

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
        registry-url: 'https://registry.npmjs.org'

    - name: Show versions
      run: |
        node --version
        pnpm --version
      shell: bash

    - name: Install
      run: pnpm install
      shell: bash
