compressionLevel: mixed

enableGlobalCache: true

nmMode: hardlinks-local

nodeLinker: node-modules

npmPublishAccess: public

npmPublishRegistry: 'https://registry.npmjs.org'

yarnPath: .yarn/releases/yarn-4.7.0.cjs
