compressionLevel: mixed

enableGlobalCache: true

nmMode: hardlinks-local

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmPublishAccess: public

npmPublishRegistry: 'https://registry.npmjs.org'

yarnPath: .yarn/releases/yarn-4.4.1.cjs
