packages:
  - 'packages/block-std'
  - 'packages/blocks'
  - 'packages/docs/main'
  - 'packages/docs/presets'
  - 'packages/global'
  - 'packages/inline'
  - 'packages/lit'
  - 'packages/playground'
  - 'packages/presets'
  - 'packages/store'
