packages:
  - 'packages/framework/block-std'
  - 'packages/framework/global'
  - 'packages/framework/inline'
  - 'packages/framework/lit'
  - 'packages/framework/store'
  - 'packages/blocks'
  - 'packages/docs'
  - 'packages/playground'
  - 'packages/presets'
