/* CSS variables. You need to handle all places where CSS variables are marked. */
export const VARIABLES = [
  '--affine-theme-mode',
  '--affine-editor-mode',
  '--affine-page-background',
  '--affine-popover-background',
  '--affine-hover-background',
  '--affine-code-background',
  '--affine-tooltip-background',
  '--affine-hub-background',
  '--affine-card-hover-background',
  '--affine-text-color',
  '--affine-secondary-text-color',
  '--affine-edgeless-text-color',
  '--affine-link-color2',
  '--affine-link-visited-color',
  '--affine-block-handle-color',
  '--affine-code-color',
  '--affine-code-block-background',
  '--affine-selected-color',
  '--affine-disable-color',
  '--affine-tooltip-color',
  '--affine-line-number-color',
  '--affine-modal-shadow',
  '--affine-popover-shadow',
  '--affine-font-h1',
  '--affine-font-h2',
  '--affine-font-h3',
  '--affine-font-h4',
  '--affine-font-h5',
  '--affine-font-h6',
  '--affine-font-base',
  '--affine-font-sm',
  '--affine-font-xs',
  '--affine-line-height',
  '--affine-z-index-modal',
  '--affine-z-index-popover',
  '--affine-font-family',
  '--affine-font-number-family',
  '--affine-font-code-family',
  '--affine-paragraph-space',
  '--affine-popover-radius',
  '--affine-editor-width',
  '--affine-zoom',
  '--affine-scale',
  '--affine-brand-color',
  '--affine-tertiary-color',
  '--affine-primary-color',
  '--affine-secondary-color',
  '--affine-background-success-color',
  '--affine-background-error-color',
  '--affine-background-processing-color',
  '--affine-background-warning-color',
  '--affine-background-primary-color',
  '--affine-background-overlay-panel-color',
  '--affine-background-secondary-color',
  '--affine-background-tertiary-color',
  '--affine-background-code-block',
  '--affine-background-modal-color',
  '--affine-text-primary-color',
  '--affine-text-secondary-color',
  '--affine-text-disable-color',
  '--affine-text-emphasis-color',
  '--affine-hover-color',
  '--affine-link-color',
  '--affine-quote-color',
  '--affine-icon-color',
  '--affine-icon-secondary',
  '--affine-border-color',
  '--affine-divider-color',
  '--affine-placeholder-color',
  '--affine-edgeless-grid-color',
  '--affine-success-color',
  '--affine-warning-color',
  '--affine-error-color',
  '--affine-processing-color',
  '--affine-black-10',
  '--affine-black-30',
  '--affine-black-50',
  '--affine-black-60',
  '--affine-black-80',
  '--affine-black-90',
  '--affine-black',
  '--affine-white-10',
  '--affine-white-30',
  '--affine-white-50',
  '--affine-white-60',
  '--affine-white-80',
  '--affine-white-90',
  '--affine-white',
  '--affine-tag-white',
  '--affine-tag-gray',
  '--affine-tag-red',
  '--affine-tag-orange',
  '--affine-tag-yellow',
  '--affine-tag-green',
  '--affine-tag-teal',
  '--affine-tag-blue',
  '--affine-tag-purple',
  '--affine-tag-pink',
  '--affine-palette-yellow',
  '--affine-palette-orange',
  '--affine-palette-tangerine',
  '--affine-palette-red',
  '--affine-palette-magenta',
  '--affine-palette-purple',
  '--affine-palette-navy',
  '--affine-palette-blue',
  '--affine-palette-green',
  '--affine-palette-grey',
  '--affine-palette-white',
  '--affine-palette-black',
] as const;

type VariablesType = typeof VARIABLES;
export type RawCssVariablesName = Extract<
  VariablesType[keyof VariablesType],
  string
>;

// It seems like we don't need to convert the CSS variable format to the JS variable format.
// type CamelCase<S extends string> =
//   S extends `${infer P1}-${infer P2}${infer P3}`
//     ? `${Lowercase<P1>}${Capitalize<CamelCase<`${P2}${P3}`>>}`
//     : `${Lowercase<S>}`;
// export type CssVariableName = Uncapitalize<CamelCase<RawCssVariablesName>>;

export type CssVariable = Record<RawCssVariablesName, string>;

export function isRawCssVariable(name: string): name is RawCssVariablesName {
  return VARIABLES.includes(name as RawCssVariablesName);
}
