export const basic3 = () => ({
  type: 'page',
  meta: {
    id: 'page:home',
    title: '',
    createDate: 1706005478224,
    tags: [],
  },
  blocks: {
    type: 'block',
    id: 'r0Tkunh54n',
    flavour: 'affine:page',
    version: 2,
    props: {
      title: {
        '$blocksuite:internal:text$': true,
        delta: [],
      },
    },
    children: [
      {
        type: 'block',
        id: 'MAGrr0VKG7',
        flavour: 'affine:surface',
        version: 5,
        props: {
          elements: {
            EbPjqOX34z: {
              index: 'a0',
              seed: 1525437043,
              xywh: '[-6138.796810364429,-3020.9727586380354,433,30]',
              rotate: 0,
              text: {
                'affine:surface:text': true,
                delta: [
                  {
                    insert: 'section1.content',
                  },
                ],
              },
              color: '--affine-palette-line-black',
              fontSize: 24,
              fontFamily: 'blocksuite:surface:Satoshi',
              fontWeight: '400',
              fontStyle: 'normal',
              textAlign: 'left',
              type: 'text',
              id: 'EbPjqOX34z',
              hasMaxWidth: true,
            },
            L94es5aqxD: {
              index: 'a1',
              seed: 1525437043,
              xywh: '[-6138.796810364429,-3083.289869297136,471.2660767553025,45]',
              rotate: 0,
              text: {
                'affine:surface:text': true,
                delta: [
                  {
                    insert: 'section1.title',
                  },
                ],
              },
              color: '--affine-palette-line-black',
              fontSize: 36,
              fontFamily: 'blocksuite:surface:Satoshi',
              fontWeight: '600',
              fontStyle: 'normal',
              textAlign: 'left',
              type: 'text',
              id: 'L94es5aqxD',
              hasMaxWidth: true,
            },
            yai4NWtp2Y: {
              index: 'a2',
              seed: 1525437043,
              xywh: '[-5530.17922930313,-2653.9171026216713,433,30]',
              rotate: 0,
              text: {
                'affine:surface:text': true,
                delta: [
                  {
                    insert: 'section2.content',
                  },
                ],
              },
              color: '--affine-palette-line-black',
              fontSize: 24,
              fontFamily: 'blocksuite:surface:Satoshi',
              fontWeight: '400',
              fontStyle: 'normal',
              textAlign: 'left',
              type: 'text',
              id: 'yai4NWtp2Y',
              hasMaxWidth: true,
            },
            '9RspcikvBf': {
              index: 'a3',
              seed: 1525437043,
              xywh: '[-5530.17922930313,-2718.973131078328,471.68585222025376,45]',
              rotate: 0,
              text: {
                'affine:surface:text': true,
                delta: [
                  {
                    insert: 'section2.title',
                  },
                ],
              },
              color: '--affine-palette-line-black',
              fontSize: 36,
              fontFamily: 'blocksuite:surface:Satoshi',
              fontWeight: '600',
              fontStyle: 'normal',
              textAlign: 'left',
              type: 'text',
              id: '9RspcikvBf',
              hasMaxWidth: true,
            },
            tayZcvDcuX: {
              index: 'a4',
              seed: 1525437043,
              xywh: '[-4922.582395015353,-3020.9727586380354,433,30]',
              rotate: 0,
              text: {
                'affine:surface:text': true,
                delta: [
                  {
                    insert: 'section3.content',
                  },
                ],
              },
              color: '--affine-palette-line-black',
              fontSize: 24,
              fontFamily: 'blocksuite:surface:Satoshi',
              fontWeight: '400',
              fontStyle: 'normal',
              textAlign: 'left',
              type: 'text',
              id: 'tayZcvDcuX',
              hasMaxWidth: true,
            },
            S5tivtMwLT: {
              index: 'a5',
              seed: 1525437043,
              xywh: '[-4922.582395015353,-3097.4563535299867,515.7700496598281,45]',
              rotate: 0,
              text: {
                'affine:surface:text': true,
                delta: [
                  {
                    insert: 'section3.title',
                  },
                ],
              },
              color: '--affine-palette-line-black',
              fontSize: 36,
              fontFamily: 'blocksuite:surface:Satoshi',
              fontWeight: '600',
              fontStyle: 'normal',
              textAlign: 'left',
              type: 'text',
              id: 'S5tivtMwLT',
              hasMaxWidth: true,
            },
          },
        },
        children: [
          {
            type: 'block',
            id: '6azqk3DU0k',
            flavour: 'affine:frame',
            version: 1,
            props: {
              title: {
                '$blocksuite:internal:text$': true,
                delta: [
                  {
                    insert: 'Frame 2',
                  },
                ],
              },
              background: '--affine-palette-transparent',
              xywh: '[-6313.475453098699,-3268.3256579512217,2000,1160]',
              index: 'a0',
            },
            children: [],
          },
          {
            type: 'block',
            id: 'SsshPkbDyF',
            flavour: 'affine:image',
            version: 1,
            props: {
              caption: 'section1.image',
              sourceId: 'CRjO8_4h62hhFurfbTa4q0Vr21Mk-RPAMnnA4nuQHaU=',
              width: 0,
              height: 0,
              index: 'Zzx',
              xywh: '[-6163.920127746937,-2530.4760655163427,483.24663476501735,349.5826719576721]',
              rotate: 0,
              size: 25725,
            },
            children: [],
          },
          {
            type: 'block',
            id: '1BWInRDdAi',
            flavour: 'affine:image',
            version: 1,
            props: {
              caption: 'section2.image',
              sourceId: 'ZTQ9L07Kne8WZANdbnXqi6g2mLM_YPz8kCQ5-0apb8g=',
              width: 0,
              height: 0,
              index: 'Zzz',
              xywh: '[-5589.269011049162,-3191.0685310227873,551.1795634920636,400.19154476950365]',
              rotate: 0,
              size: 24008,
            },
            children: [],
          },
          {
            type: 'block',
            id: 'w52iAXNC7J',
            flavour: 'affine:image',
            version: 1,
            props: {
              caption: 'section3.image',
              sourceId: 'n8SqfXn8bctbF_bozUwOk3ewy4l4sBJfH7izAQLaJhM=',
              width: 0,
              height: 0,
              index: 'ZzzV',
              xywh: '[-4928.552364853417,-2554.167242979329,527.7099893359582,362.0988756613756]',
              rotate: 0,
              size: 27476,
            },
            children: [],
          },
        ],
      },
    ],
  },
});
