export const basic4 = () => ({
  type: 'page',
  meta: {
    id: 'page:home',
    title: '',
    createDate: 1706005478224,
    tags: [],
  },
  blocks: {
    type: 'block',
    id: 'r0Tkunh54n',
    flavour: 'affine:page',
    version: 2,
    props: {
      title: {
        '$blocksuite:internal:text$': true,
        delta: [],
      },
    },
    children: [
      {
        type: 'block',
        id: 'MAGrr0VKG7',
        flavour: 'affine:surface',
        version: 5,
        props: {
          elements: {
            FkFOVB1iqc: {
              index: 'a0',
              seed: 1525437043,
              xywh: '[-1326.0809860427576,-1037.0413479728115,771,45]',
              rotate: 0,
              text: {
                'affine:surface:text': true,
                delta: [
                  {
                    insert: 'section4.title',
                  },
                ],
              },
              color: '--affine-palette-line-black',
              fontSize: 36,
              fontFamily: 'blocksuite:surface:Satoshi',
              fontWeight: '600',
              fontStyle: 'normal',
              textAlign: 'left',
              type: 'text',
              id: 'FkFOVB1iqc',
              hasMaxWidth: true,
            },
            RIh4YbzZTs: {
              index: 'a1',
              seed: 1525437043,
              xywh: '[-1326.0809860427576,-1426.6106639028965,828.1901444646171,300]',
              rotate: 0,
              text: {
                'affine:surface:text': true,
                delta: [
                  {
                    insert: 'section2.content',
                  },
                ],
              },
              color: '--affine-palette-line-black',
              fontSize: 27.58481343934764,
              fontFamily: 'blocksuite:surface:Satoshi',
              fontWeight: '400',
              fontStyle: 'normal',
              textAlign: 'left',
              type: 'text',
              id: 'RIh4YbzZTs',
              hasMaxWidth: true,
            },
            fC2miJGtfT: {
              index: 'a2',
              seed: 1525437043,
              xywh: '[-2220.0637830944747,-1495.4354372093983,755,45]',
              rotate: 0,
              text: {
                'affine:surface:text': true,
                delta: [
                  {
                    insert: 'section1.title',
                  },
                ],
              },
              color: '--affine-palette-line-black',
              fontSize: 36,
              fontFamily: 'blocksuite:surface:Satoshi',
              fontWeight: '600',
              fontStyle: 'normal',
              textAlign: 'left',
              type: 'text',
              id: 'fC2miJGtfT',
              hasMaxWidth: true,
            },
            'TkwGgI-mi4': {
              index: 'a3',
              seed: 1525437043,
              xywh: '[-2220.0637830944747,-1434.2328576595216,368.3516000236491,300]',
              rotate: 0,
              text: {
                'affine:surface:text': true,
                delta: [
                  {
                    insert: 'section1.content',
                  },
                ],
              },
              color: '--affine-palette-line-black',
              fontSize: 30.097755005300126,
              fontFamily: 'blocksuite:surface:Satoshi',
              fontWeight: '400',
              fontStyle: 'normal',
              textAlign: 'left',
              type: 'text',
              id: 'TkwGgI-mi4',
              hasMaxWidth: true,
            },
            qXxm8_BSX9: {
              index: 'a4',
              seed: 1525437043,
              xywh: '[-1326.0809860427576,-1495.4354372093983,751,45]',
              rotate: 0,
              text: {
                'affine:surface:text': true,
                delta: [
                  {
                    insert: 'section2.title',
                  },
                ],
              },
              color: '--affine-palette-line-black',
              fontSize: 36,
              fontFamily: 'blocksuite:surface:Satoshi',
              fontWeight: '600',
              fontStyle: 'normal',
              textAlign: 'left',
              type: 'text',
              id: 'qXxm8_BSX9',
              hasMaxWidth: true,
            },
            '7Y_8DWGOYm': {
              index: 'a7',
              seed: 1525437043,
              xywh: '[-2220.0637830944747,-947.838273804369,762.1937558482443,300]',
              rotate: 0,
              text: {
                'affine:surface:text': true,
                delta: [
                  {
                    insert: 'section3.content',
                  },
                ],
              },
              color: '--affine-palette-line-black',
              fontSize: 26.37579683020094,
              fontFamily: 'blocksuite:surface:Satoshi',
              fontWeight: '400',
              fontStyle: 'normal',
              textAlign: 'left',
              type: 'text',
              id: '7Y_8DWGOYm',
              hasMaxWidth: true,
            },
            SnXq4Umb2n: {
              index: 'a8',
              seed: 1525437043,
              xywh: '[-2220.0637830944747,-1020.1673474354172,748,45]',
              rotate: 0,
              text: {
                'affine:surface:text': true,
                delta: [
                  {
                    insert: 'section3.title',
                  },
                ],
              },
              color: '--affine-palette-line-black',
              fontSize: 36,
              fontFamily: 'blocksuite:surface:Satoshi',
              fontWeight: '600',
              fontStyle: 'normal',
              textAlign: 'left',
              type: 'text',
              id: 'SnXq4Umb2n',
              hasMaxWidth: true,
            },
            cv_IRos5mt: {
              index: 'a9',
              seed: 1525437043,
              xywh: '[-936.527845229799,-953.838273804369,398,300]',
              rotate: 0,
              text: {
                'affine:surface:text': true,
                delta: [
                  {
                    insert: 'section4.content',
                  },
                ],
              },
              color: '--affine-palette-line-black',
              fontSize: 28.53402967020424,
              fontFamily: 'blocksuite:surface:Satoshi',
              fontWeight: '400',
              fontStyle: 'normal',
              textAlign: 'left',
              type: 'text',
              id: 'cv_IRos5mt',
              hasMaxWidth: true,
            },
          },
        },
        children: [
          {
            type: 'block',
            id: 'shlNbjVmLt',
            flavour: 'affine:frame',
            version: 1,
            props: {
              title: {
                '$blocksuite:internal:text$': true,
                delta: [
                  {
                    insert: 'title',
                  },
                ],
              },
              background: '--affine-palette-transparent',
              xywh: '[-2383.92381869001,-1657.9461737879421,2000,1160]',
              index: 'a0',
            },
            children: [],
          },
          {
            type: 'block',
            id: 'e1dwkZnkiU',
            flavour: 'affine:image',
            version: 1,
            props: {
              caption: 'section1.image',
              sourceId: 'iEQ1Em4eumfvM-hHFiJyY1NwhMYI2oUCIKxNp6J_BRs=',
              width: 0,
              height: 0,
              index: 'Zzt',
              xywh: '[-1791.1999662554751,-1392.129647103712,394.6340868550005,331.4926329582004]',
              rotate: 0,
              size: 9724,
            },
            children: [],
          },
          {
            type: 'block',
            id: '5-7NxvUuaR',
            flavour: 'affine:image',
            version: 1,
            props: {
              caption: 'section4.image',
              sourceId: '3PKKm0--GNZGBAm654LwcrMCg4dv7iMBvaP6jmcQvkk=',
              width: 0,
              height: 0,
              index: 'Zzx',
              xywh: '[-1385.138730901247,-953.838273804369,397.6483769971952,302.970191997863]',
              rotate: 0,
              size: 10362,
            },
            children: [],
          },
        ],
      },
    ],
  },
});
