export default {
  name: '2h5w critical questions',
  type: 'template',
  preview: 'https://cdn.affine.pro/templates/cover/2h5w.png',
  content: {
    type: 'page',
    meta: {
      id: 'page:home',
      title: '',
      createDate: 1702892304802,
      tags: [],
    },
    blocks: {
      type: 'block',
      id: 'block:9PKzZjyndk',
      flavour: 'affine:page',
      props: {
        title: {
          '$blocksuite:internal:text$': true,
          delta: [],
        },
      },
      children: [
        {
          type: 'block',
          id: 'block:lxGBw605Ce',
          flavour: 'affine:surface',
          props: {
            elements: {
              laToEg5JOl: {
                type: 'shape',
                xywh: '[-201.61938587621069,-529.1345070749973,1473.389985368025,257.1885476538611]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0,
                filled: true,
                fillColor: '--affine-palette-shape-magenta',
                strokeWidth: 4,
                strokeColor: '--affine-palette-transparent',
                strokeStyle: 'solid',
                roughness: 1.4,
                id: 'laToEg5JOl',
                index: 'a0',
                seed: 1351664447,
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:Kalam',
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert:
                        'This question seeks to identify the people involved or affected by the subject at hand.',
                    },
                  ],
                },
                fontWeight: '400',
                fontStyle: 'normal',
                fontSize: 40,
                textAlign: 'left',
              },
              zwvTDyNjaf: {
                type: 'text',
                xywh: '[-1870.3781936679968,-868.2245118314581,826,459]',
                rotate: 0,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert:
                        'The 2H5W template is a structured format for problem-solving and analysis, focusing on two "Hows" (How, How Much) and five "Whys" (Why, Who, Where, When, What). \n\nThis template guides a thorough exploration of a situation or problem, facilitating comprehensive understanding and effective decision-making.',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontSize: 36,
                fontFamily: 'blocksuite:surface:Poppins',
                fontWeight: '400',
                fontStyle: 'normal',
                textAlign: 'left',
                id: 'zwvTDyNjaf',
                index: 'a1',
                seed: 2142683235,
                hasMaxWidth: true,
              },
              CsKLAV09It: {
                type: 'shape',
                xywh: '[-201.61938587621069,-251.3797849106202,1473.389985368025,257.1885476538611]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0,
                filled: true,
                fillColor: '--affine-palette-shape-purple',
                strokeWidth: 4,
                strokeColor: '--affine-palette-transparent',
                strokeStyle: 'solid',
                roughness: 1.4,
                id: 'CsKLAV09It',
                index: 'a3',
                seed: 987237184,
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:Kalam',
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert:
                        'This question aims to define the subject, event, or issue being discussed or analyzed.',
                    },
                  ],
                },
                fontWeight: '400',
                fontStyle: 'normal',
                fontSize: 40,
                textAlign: 'left',
              },
              Q1w4z5F4GY: {
                type: 'shape',
                xywh: '[-201.61938587621069,26.374937253756883,1473.389985368025,257.1885476538611]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0,
                filled: true,
                fillColor: '--affine-palette-shape-tangerine',
                strokeWidth: 4,
                strokeColor: '--affine-palette-transparent',
                strokeStyle: 'solid',
                roughness: 1.4,
                id: 'Q1w4z5F4GY',
                index: 'a4',
                seed: 1442831124,
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:Kalam',
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert:
                        'This addresses the location or context in which the subject or issue exists or occurs. ',
                    },
                  ],
                },
                fontWeight: '400',
                fontStyle: 'normal',
                fontSize: 40,
                textAlign: 'left',
              },
              'TLdrgB-bmL': {
                type: 'shape',
                xywh: '[-201.61938587621069,304.129659418134,1473.389985368025,257.1885476538611]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0,
                filled: true,
                fillColor: '--affine-palette-shape-green',
                strokeWidth: 4,
                strokeColor: '--affine-palette-transparent',
                strokeStyle: 'solid',
                roughness: 1.4,
                id: 'TLdrgB-bmL',
                index: 'a5',
                seed: 526447072,
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:Kalam',
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert:
                        'This question is about timing. It covers the duration, frequency, historical context, or future dates related to the topic.',
                    },
                  ],
                },
                fontWeight: '400',
                fontStyle: 'normal',
                fontSize: 40,
                textAlign: 'left',
              },
              s8fodn6F2a: {
                type: 'text',
                xywh: '[-492.14417902997377,-464.54023324806656,225.53598022460938,128]',
                rotate: 0,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Who',
                    },
                  ],
                },
                color: '--affine-palette-line-magenta',
                fontSize: 128,
                fontFamily: 'blocksuite:surface:Kalam',
                fontWeight: '600',
                fontStyle: 'normal',
                textAlign: 'left',
                id: 's8fodn6F2a',
                index: 'a6',
                seed: 352833548,
              },
              DZnhiDZZ6w: {
                type: 'text',
                xywh: '[-547.1841875748956,-186.7855110836895,280.57598876953125,128]',
                rotate: 0,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'What',
                    },
                  ],
                },
                color: '--affine-palette-line-purple',
                fontSize: 128,
                fontFamily: 'blocksuite:surface:Kalam',
                fontWeight: '600',
                fontStyle: 'normal',
                textAlign: 'left',
                id: 'DZnhiDZZ6w',
                index: 'aD',
                seed: 659508098,
              },
              'BKF-_HB-rM': {
                type: 'text',
                xywh: '[-581.4882036881769,90.9692110806876,314.8800048828125,128]',
                rotate: 0,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'where',
                    },
                  ],
                },
                color: '--affine-palette-line-tangerine',
                fontSize: 128,
                fontFamily: 'blocksuite:surface:Kalam',
                fontWeight: '600',
                fontStyle: 'normal',
                textAlign: 'left',
                id: 'BKF-_HB-rM',
                index: 'aE',
                seed: 1125861801,
              },
              '-d71rCScfv': {
                type: 'text',
                xywh: '[-562.2881914811456,368.7239332450647,295.67999267578125,128]',
                rotate: 0,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'When',
                    },
                  ],
                },
                color: '--affine-palette-line-green',
                fontSize: 128,
                fontFamily: 'blocksuite:surface:Kalam',
                fontWeight: '600',
                fontStyle: 'normal',
                textAlign: 'left',
                id: '-d71rCScfv',
                index: 'aF',
                seed: 1242708572,
              },
              'z-QEAae5Rt': {
                type: 'text',
                xywh: '[-500.8481890397394,646.4786554094418,234.239990234375,128]',
                rotate: 0,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Why',
                    },
                  ],
                },
                color: '--affine-palette-line-yellow',
                fontSize: 128,
                fontFamily: 'blocksuite:surface:Kalam',
                fontWeight: '600',
                fontStyle: 'normal',
                textAlign: 'left',
                id: 'z-QEAae5Rt',
                index: 'aG',
                seed: 753535819,
              },
              '2bY8WzF4_h': {
                type: 'text',
                xywh: '[-491.7601763444269,924.2333775738189,225.1519775390625,128]',
                rotate: 0,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'How',
                    },
                  ],
                },
                color: '--affine-palette-line-orange',
                fontSize: 128,
                fontFamily: 'blocksuite:surface:Kalam',
                fontWeight: '600',
                fontStyle: 'normal',
                textAlign: 'left',
                id: '2bY8WzF4_h',
                index: 'aH',
                seed: 1590463856,
              },
              Y5jr8zSDoo: {
                type: 'text',
                xywh: '[-828.2721392350519,1201.9880997381958,561.6639404296875,128]',
                rotate: 0,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'How much',
                    },
                  ],
                },
                color: '--affine-palette-line-blue',
                fontSize: 128,
                fontFamily: 'blocksuite:surface:Kalam',
                fontWeight: '600',
                fontStyle: 'normal',
                textAlign: 'left',
                id: 'Y5jr8zSDoo',
                index: 'aI',
                seed: 1319055993,
              },
              gI3omnjjik: {
                type: 'shape',
                xywh: '[-201.61938587621069,581.8843815825111,1473.389985368025,257.1885476538611]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0,
                filled: true,
                fillColor: '--affine-palette-shape-yellow',
                strokeWidth: 4,
                strokeColor: '--affine-palette-transparent',
                strokeStyle: 'solid',
                roughness: 1.4,
                id: 'gI3omnjjik',
                index: 'aJ',
                seed: 1772724211,
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:Kalam',
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert:
                        'This seeks to uncover reasons, motivations, causes, or purposes behind the subject.',
                    },
                  ],
                },
                fontWeight: '400',
                fontStyle: 'normal',
                fontSize: 40,
                textAlign: 'left',
              },
              xHDuIjj7x9: {
                type: 'shape',
                xywh: '[-201.61938587621069,859.6391037468882,1473.389985368025,257.1885476538611]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0,
                filled: true,
                fillColor: '--affine-palette-shape-orange',
                strokeWidth: 4,
                strokeColor: '--affine-palette-transparent',
                strokeStyle: 'solid',
                roughness: 1.4,
                id: 'xHDuIjj7x9',
                index: 'aK',
                seed: 1757735583,
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:Kalam',
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert:
                        'This is about the method, process, or manner in which something happens or is done.',
                    },
                  ],
                },
                fontWeight: '400',
                fontStyle: 'normal',
                fontSize: 40,
                textAlign: 'left',
              },
              'BEDdddqjs-': {
                type: 'shape',
                xywh: '[-201.61938587621057,1137.3938259112651,1473.389985368025,257.1885476538611]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0,
                filled: true,
                fillColor: '--affine-palette-shape-blue',
                strokeWidth: 4,
                strokeColor: '--affine-palette-transparent',
                strokeStyle: 'solid',
                roughness: 1.4,
                id: 'BEDdddqjs-',
                index: 'aL',
                seed: 1910023393,
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:Kalam',
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert:
                        'This question deals with quantities, volumes, extents, or degrees. ',
                    },
                  ],
                },
                fontWeight: '400',
                fontStyle: 'normal',
                fontSize: 40,
                textAlign: 'left',
              },
              eZmiP6bKVg: {
                type: 'text',
                xywh: '[-744.0789331182913,-960.7827003158441,2067,300]',
                rotate: 0,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: '2h5W Critical questions ',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontSize: 200,
                fontFamily: 'blocksuite:surface:Kalam',
                fontWeight: '600',
                fontStyle: 'normal',
                textAlign: 'left',
                id: 'eZmiP6bKVg',
                index: 'aN',
                seed: 1671166181,
              },
              zA3T9hK74M: {
                type: 'text',
                xywh: '[-744.0789331182913,-724.7827003158441,2005.9195556640625,80]',
                rotate: 0,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert:
                        'things to think about  when  someone has something to say',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontSize: 80,
                fontFamily: 'blocksuite:surface:Kalam',
                fontWeight: '400',
                fontStyle: 'normal',
                textAlign: 'left',
                id: 'zA3T9hK74M',
                index: 'aO',
                seed: 1655939011,
              },
              '9VCtL0aFBB': {
                type: 'group',
                children: {
                  'affine:surface:ymap': true,
                  json: {
                    zwvTDyNjaf: true,
                    'block:tTJGH7sGeG': true,
                  },
                },
                title: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Group 1',
                    },
                  ],
                },
                id: '9VCtL0aFBB',
                index: 'aP',
                seed: 1619512515,
              },
            },
          },
          children: [],
        },
        {
          type: 'block',
          id: 'block:tTJGH7sGeG',
          flavour: 'affine:note',
          props: {
            xywh: '[-1927.2781877665518,-940.9087904148496,939.7999881971101,604.368557166783]',
            background: '--affine-background-secondary-color',
            index: 'Zz',
            displayMode: 'edgeless',
            hidden: false,
            edgeless: {
              style: {
                borderRadius: 8,
                borderSize: 4,
                borderStyle: 'solid',
                shadowType: '--affine-note-shadow-film',
              },
              collapse: true,
            },
          },
          children: [
            {
              type: 'block',
              id: 'block:0-Cp51KFEU',
              flavour: 'affine:paragraph',
              props: {
                type: 'text',
                text: {
                  '$blocksuite:internal:text$': true,
                  delta: [],
                },
              },
              children: [],
            },
          ],
        },
      ],
    },
  },
};
