export default {
  name: 'Fishbone',
  type: 'template',
  preview: 'https://cdn.affine.pro/templates/cover/fishbone.png',
  assets: {
    'lrxxmLPiDeoDlEDUuBQp51JXetfPiG7l7HUzuKzDKuo=':
      'https://cdn.affine.pro/templates/assets/lrxxmLPiDeoDlEDUuBQp51JXetfPiG7l7HUzuKzDKuo=.png',
    'YUo3S6WvBWTO3fcRR1iUKLXVFxnILmP-VTwdM3ai-h0=':
      'https://cdn.affine.pro/templates/assets/YUo3S6WvBWTO3fcRR1iUKLXVFxnILmP-VTwdM3ai-h0=.png',
  },
  content: {
    type: 'page',
    meta: {
      id: 'page:t5aZ5PCNMc',
      title: '',
      createDate: 1703046043802,
      tags: [],
    },
    blocks: {
      type: 'block',
      id: 'block:pjMZBFnYM9',
      flavour: 'affine:page',
      props: {
        title: {
          '$blocksuite:internal:text$': true,
          delta: [],
        },
      },
      children: [
        {
          type: 'block',
          id: 'block:eQX5lcfl5l',
          flavour: 'affine:surface',
          props: {
            elements: {
              '1tnkLD1v85': {
                type: 'shape',
                xywh: '[90.82530748541876,-473.3367926720803,1300.0535907679186,69]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0,
                filled: true,
                fillColor: '--affine-palette-shape-black',
                strokeWidth: 4,
                strokeColor: '--affine-palette-line-yellow',
                strokeStyle: 'none',
                roughness: 1.4,
                id: '1tnkLD1v85',
                index: 'ai',
                seed: 898661492,
                color: '--affine-palette-line-white',
                text: {
                  'affine:surface:text': true,
                  delta: [],
                },
                fontFamily: 'blocksuite:surface:Inter',
                fontSize: 24,
              },
              Gd2Q2miQkl: {
                type: 'shape',
                xywh: '[190.43939980770665,-1661.643968542211,460.09024318240836,179]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0.1,
                filled: false,
                fillColor: '--affine-palette-transparent',
                strokeWidth: 12,
                strokeColor: '--affine-palette-line-black',
                strokeStyle: 'solid',
                roughness: 1.4,
                id: 'Gd2Q2miQkl',
                index: 'aj',
                seed: 100229520,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Category',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:BebasNeue',
                fontSize: 64,
                fontWeight: '400',
                fontStyle: 'normal',
              },
              XH93icAbGO: {
                type: 'shape',
                xywh: '[-215.7102635998933,-1266.5553016096458,460.09024318240836,179]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0.1,
                filled: false,
                fillColor: '--affine-palette-transparent',
                strokeWidth: 12,
                strokeColor: '--affine-palette-line-black',
                strokeStyle: 'dash',
                roughness: 1.4,
                id: 'XH93icAbGO',
                index: 'ak',
                seed: 1774361779,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Item 2',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:BebasNeue',
                fontSize: 64,
                fontWeight: '400',
                fontStyle: 'normal',
              },
              'iDmTM-bSqM': {
                type: 'shape',
                xywh: '[-76.60249877147064,-867.4460471408631,460.09024318240836,179]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0.1,
                filled: false,
                fillColor: '--affine-palette-transparent',
                strokeWidth: 12,
                strokeColor: '--affine-palette-line-black',
                strokeStyle: 'dash',
                roughness: 1.4,
                id: 'iDmTM-bSqM',
                index: 'al',
                seed: 1975714611,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Item 1',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:BebasNeue',
                fontSize: 64,
                fontWeight: '400',
                fontStyle: 'normal',
              },
              ZpYgUk5Bvw: {
                type: 'shape',
                xywh: '[-76.60249877147064,-189.2275382032975,460.09024318240836,179]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0.1,
                filled: false,
                fillColor: '--affine-palette-transparent',
                strokeWidth: 12,
                strokeColor: '--affine-palette-line-black',
                strokeStyle: 'dash',
                roughness: 1.4,
                id: 'ZpYgUk5Bvw',
                index: 'am',
                seed: 2028054473,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Item 1',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:BebasNeue',
                fontSize: 64,
                fontWeight: '400',
                fontStyle: 'normal',
              },
              _OQY2CmBkj: {
                type: 'shape',
                xywh: '[-215.7102635998933,209.88171626548524,460.09024318240836,179]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0.1,
                filled: false,
                fillColor: '--affine-palette-transparent',
                strokeWidth: 12,
                strokeColor: '--affine-palette-line-black',
                strokeStyle: 'dash',
                roughness: 1.4,
                id: '_OQY2CmBkj',
                index: 'an',
                seed: 1101297049,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Item 2',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:BebasNeue',
                fontSize: 64,
                fontWeight: '400',
                fontStyle: 'normal',
              },
              '5SUEBaLHe6': {
                type: 'shape',
                xywh: '[192.03412042789043,608.9909707342675,460.09024318240836,178.5278226189996]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0.1,
                filled: false,
                fillColor: '--affine-palette-transparent',
                strokeWidth: 12,
                strokeColor: '--affine-palette-line-black',
                strokeStyle: 'solid',
                roughness: 1.4,
                id: '5SUEBaLHe6',
                index: 'ao',
                seed: 96786809,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Category',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:BebasNeue',
                fontSize: 64,
                fontWeight: '400',
                fontStyle: 'normal',
              },
              'Jpd6g-E0Vs': {
                type: 'connector',
                mode: 0,
                strokeWidth: 12,
                stroke: '--affine-palette-line-black',
                strokeStyle: 'solid',
                roughness: 1.4,
                source: {
                  id: 'Gd2Q2miQkl',
                  position: [0.5, 1],
                },
                target: {
                  id: '1tnkLD1v85',
                  position: [0.5, 0],
                },
                id: 'Jpd6g-E0Vs',
                index: 'ap',
                seed: 668844487,
                rearEndpointStyle: 'Triangle',
              },
              qFjjhDXlTU: {
                type: 'connector',
                mode: 0,
                strokeWidth: 12,
                stroke: '--affine-palette-line-black',
                strokeStyle: 'solid',
                roughness: 1.4,
                source: {
                  id: '5SUEBaLHe6',
                  position: [0.5, 0],
                },
                target: {
                  id: '1tnkLD1v85',
                  position: [0.5, 1],
                },
                id: 'qFjjhDXlTU',
                index: 'aq',
                seed: 1141491660,
                rearEndpointStyle: 'Triangle',
              },
              '5vVci0f2U4': {
                rearEndpointStyle: 'None',
                type: 'connector',
                mode: 0,
                strokeWidth: 12,
                stroke: '--affine-palette-line-black',
                strokeStyle: 'dash',
                roughness: 1.4,
                source: {
                  id: 'XH93icAbGO',
                  position: [1, 0.5],
                },
                target: {
                  position: [517.7238488105149, -1179.3735758624255],
                },
                id: '5vVci0f2U4',
                index: 'ar',
                seed: 1607660152,
                xywh: '[244.37997958251506,-1124.6492930708316,302.2653505427783,1]',
              },
              vGtWzHN83M: {
                rearEndpointStyle: 'None',
                type: 'connector',
                mode: 0,
                strokeWidth: 12,
                stroke: '--affine-palette-line-black',
                strokeStyle: 'dash',
                roughness: 1.4,
                source: {
                  id: 'iDmTM-bSqM',
                  position: [1, 0.5],
                },
                target: {
                  position: [644.2224984714358, -777.7393530478234],
                },
                id: 'vGtWzHN83M',
                index: 'as',
                seed: 744160879,
                xywh: '[383.4877444109377,-724.9776586540529,311.0180004832295,1]',
              },
              s2804zJoIH: {
                type: 'connector',
                mode: 0,
                strokeWidth: 12,
                stroke: '--affine-palette-line-black',
                strokeStyle: 'dash',
                roughness: 1.4,
                source: {
                  id: 'ZpYgUk5Bvw',
                  position: [1, 0.5],
                },
                target: {
                  position: [643.7343634232523, -100.31279469185756],
                },
                id: 's2804zJoIH',
                index: 'at',
                seed: 767016892,
                rearEndpointStyle: 'None',
                xywh: '[383.4877444109377,-46.785162908058986,312.71597593490213,1]',
              },
              k_IkfIzeTb: {
                type: 'connector',
                mode: 0,
                rearEndpointStyle: 'None',
                strokeWidth: 12,
                stroke: '--affine-palette-line-black',
                strokeStyle: 'dash',
                roughness: 1.4,
                source: {
                  id: '_OQY2CmBkj',
                  position: [1, 0.5],
                },
                target: {
                  position: [518.2152623732262, 297.85112944355745],
                },
                id: 'k_IkfIzeTb',
                index: 'au',
                seed: 433287472,
                xywh: '[244.37997958251506,352.35010475229547,302.4493968329945,1]',
              },
              iOIrnhoxwg: {
                type: 'group',
                children: {
                  'affine:surface:ymap': true,
                  json: {
                    '1tnkLD1v85': true,
                    Gd2Q2miQkl: true,
                    XH93icAbGO: true,
                    'iDmTM-bSqM': true,
                    ZpYgUk5Bvw: true,
                    _OQY2CmBkj: true,
                    '5SUEBaLHe6': true,
                    'Jpd6g-E0Vs': true,
                    qFjjhDXlTU: true,
                    '5vVci0f2U4': true,
                    vGtWzHN83M: true,
                    s2804zJoIH: true,
                    k_IkfIzeTb: true,
                  },
                },
                title: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Group 3',
                    },
                  ],
                },
                id: 'iOIrnhoxwg',
                index: 'av',
                seed: 2071717743,
              },
              SIhEnNT7R6: {
                type: 'shape',
                xywh: '[1356.7165511723326,-473.33679267208055,1300.0535907679186,69]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0,
                filled: true,
                fillColor: '--affine-palette-shape-black',
                strokeWidth: 4,
                strokeColor: '--affine-palette-line-yellow',
                strokeStyle: 'none',
                roughness: 1.4,
                id: 'SIhEnNT7R6',
                index: 'aw',
                seed: 77230658,
                color: '--affine-palette-line-white',
                text: {
                  'affine:surface:text': true,
                  delta: [],
                },
                fontFamily: 'blocksuite:surface:Inter',
                fontSize: 24,
              },
              M5s7kM2i3I: {
                type: 'shape',
                xywh: '[1457.925364114804,-1665.1923786974282,460.09024318240836,178.5278226189996]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0.1,
                filled: false,
                fillColor: '--affine-palette-transparent',
                strokeWidth: 12,
                strokeColor: '--affine-palette-line-black',
                strokeStyle: 'solid',
                roughness: 1.4,
                id: 'M5s7kM2i3I',
                index: 'ax',
                seed: 1851160611,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Category',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:BebasNeue',
                fontSize: 64,
                fontWeight: '400',
                fontStyle: 'normal',
              },
              GGd5rP0AqD: {
                type: 'shape',
                xywh: '[1050.1809800870203,-1266.5553016096458,460.09024318240836,179]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0.1,
                filled: false,
                fillColor: '--affine-palette-transparent',
                strokeWidth: 12,
                strokeColor: '--affine-palette-line-black',
                strokeStyle: 'dash',
                roughness: 1.4,
                id: 'GGd5rP0AqD',
                index: 'ay',
                seed: 35879121,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Item 2',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:BebasNeue',
                fontSize: 64,
                fontWeight: '400',
                fontStyle: 'normal',
              },
              '8abHg3duFe': {
                type: 'shape',
                xywh: '[1189.288744915443,-867.4460471408631,460.09024318240836,179]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0.1,
                filled: false,
                fillColor: '--affine-palette-transparent',
                strokeWidth: 12,
                strokeColor: '--affine-palette-line-black',
                strokeStyle: 'dash',
                roughness: 1.4,
                id: '8abHg3duFe',
                index: 'az',
                seed: 139337416,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Item 1',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:BebasNeue',
                fontSize: 64,
                fontWeight: '400',
                fontStyle: 'normal',
              },
              'v57sHm39O-': {
                type: 'shape',
                xywh: '[1189.288744915443,-189.2275382032979,460.09024318240836,179]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0.1,
                filled: false,
                fillColor: '--affine-palette-transparent',
                strokeWidth: 12,
                strokeColor: '--affine-palette-line-black',
                strokeStyle: 'dash',
                roughness: 1.4,
                id: 'v57sHm39O-',
                index: 'b00',
                seed: 935249019,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Item 1',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:BebasNeue',
                fontSize: 64,
                fontWeight: '400',
                fontStyle: 'normal',
              },
              qM3icEQG3J: {
                type: 'shape',
                xywh: '[1050.1809800870203,209.88171626548495,460.09024318240836,179]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0.1,
                filled: false,
                fillColor: '--affine-palette-transparent',
                strokeWidth: 12,
                strokeColor: '--affine-palette-line-black',
                strokeStyle: 'dash',
                roughness: 1.4,
                id: 'qM3icEQG3J',
                index: 'b01',
                seed: 1004110600,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Item 2',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:BebasNeue',
                fontSize: 64,
                fontWeight: '400',
                fontStyle: 'normal',
              },
              KfIfSzI2tT: {
                type: 'shape',
                xywh: '[1457.925364114804,608.9909707342674,460.09024318240836,178.5278226189996]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0.1,
                filled: false,
                fillColor: '--affine-palette-transparent',
                strokeWidth: 12,
                strokeColor: '--affine-palette-line-black',
                strokeStyle: 'solid',
                roughness: 1.4,
                id: 'KfIfSzI2tT',
                index: 'b02',
                seed: 1132643231,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Category',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:BebasNeue',
                fontSize: 64,
                fontWeight: '400',
                fontStyle: 'normal',
              },
              _Ox3ph6HYJ: {
                type: 'connector',
                mode: 0,
                strokeWidth: 12,
                stroke: '--affine-palette-line-black',
                strokeStyle: 'solid',
                roughness: 1.4,
                source: {
                  id: 'M5s7kM2i3I',
                  position: [0.5, 1],
                },
                target: {
                  id: 'SIhEnNT7R6',
                  position: [0.5, 0],
                },
                id: '_Ox3ph6HYJ',
                index: 'b03',
                seed: 60467959,
                rearEndpointStyle: 'Triangle',
              },
              DmDQxuoMGu: {
                type: 'connector',
                mode: 0,
                strokeWidth: 12,
                stroke: '--affine-palette-line-black',
                strokeStyle: 'solid',
                roughness: 1.4,
                source: {
                  id: 'KfIfSzI2tT',
                  position: [0.5, 0],
                },
                target: {
                  id: 'SIhEnNT7R6',
                  position: [0.5, 1],
                },
                id: 'DmDQxuoMGu',
                index: 'b04',
                seed: 174420372,
                rearEndpointStyle: 'Triangle',
              },
              '1q0J_wl6Db': {
                type: 'connector',
                mode: 0,
                strokeWidth: 12,
                stroke: '--affine-palette-line-black',
                strokeStyle: 'dash',
                roughness: 1.4,
                source: {
                  id: 'GGd5rP0AqD',
                  position: [1, 0.5],
                },
                target: {
                  position: [1783.6150924974281, -1179.3735758624257],
                },
                rearEndpointStyle: 'None',
                id: '1q0J_wl6Db',
                index: 'b05',
                seed: 1220810882,
                xywh: '[1510.2712232694287,-1126.4051873756157,273.34386922799945,2.318274252779929]',
              },
              '2WyN6taeRs': {
                type: 'connector',
                mode: 0,
                strokeWidth: 12,
                stroke: '--affine-palette-line-black',
                strokeStyle: 'dash',
                roughness: 1.4,
                source: {
                  id: '8abHg3duFe',
                  position: [1, 0.5],
                },
                target: {
                  position: [1910.1137421583487, -777.7393530478237],
                },
                rearEndpointStyle: 'None',
                id: '2WyN6taeRs',
                index: 'b06',
                seed: 362029486,
                xywh: '[1649.3789880978513,-724.9776586540531,260.7347540604974,1]',
              },
              xixw1aMPE3: {
                type: 'connector',
                mode: 0,
                strokeWidth: 12,
                stroke: '--affine-palette-line-black',
                strokeStyle: 'dash',
                roughness: 1.4,
                source: {
                  id: 'v57sHm39O-',
                  position: [1, 0.5],
                },
                target: {
                  position: [1909.625607110166, -100.31279469185785],
                },
                id: 'xixw1aMPE3',
                index: 'b07',
                seed: 1517862158,
                rearEndpointStyle: 'None',
                xywh: '[1649.3789880978513,-47.344406205047854,260.24661901231457,1]',
              },
              jHY1J8LRnR: {
                type: 'connector',
                mode: 0,
                strokeWidth: 12,
                stroke: '--affine-palette-line-black',
                strokeStyle: 'dash',
                roughness: 1.4,
                source: {
                  id: 'qM3icEQG3J',
                  position: [1, 0.5],
                },
                target: {
                  position: [1784.1065060601395, 297.8511294435571],
                },
                rearEndpointStyle: 'None',
                id: 'jHY1J8LRnR',
                index: 'b08',
                seed: 450690986,
                xywh: '[1510.2712232694287,350.8195179303671,273.83528279071083,1.530586821927841]',
              },
              'zd--iqIpeR': {
                type: 'group',
                children: {
                  'affine:surface:ymap': true,
                  json: {
                    SIhEnNT7R6: true,
                    M5s7kM2i3I: true,
                    GGd5rP0AqD: true,
                    '8abHg3duFe': true,
                    'v57sHm39O-': true,
                    qM3icEQG3J: true,
                    KfIfSzI2tT: true,
                    _Ox3ph6HYJ: true,
                    DmDQxuoMGu: true,
                    '1q0J_wl6Db': true,
                    '2WyN6taeRs': true,
                    xixw1aMPE3: true,
                    jHY1J8LRnR: true,
                  },
                },
                title: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Group 2',
                    },
                  ],
                },
                id: 'zd--iqIpeR',
                index: 'b09',
                seed: 1719136077,
                xywh: '[3017.468060106568,-1789.2269905718442,1606.589161853231,2452.7111720506955]',
              },
              '59EeImMqdn': {
                type: 'shape',
                xywh: '[2643.770603819579,-473.3367926720804,1300.0535907679186,69]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0,
                filled: true,
                fillColor: '--affine-palette-shape-black',
                strokeWidth: 4,
                strokeColor: '--affine-palette-line-yellow',
                strokeStyle: 'none',
                roughness: 1.4,
                id: '59EeImMqdn',
                index: 'b0A',
                seed: 267669734,
                color: '--affine-palette-line-white',
                text: {
                  'affine:surface:text': true,
                  delta: [],
                },
                fontFamily: 'blocksuite:surface:Inter',
                fontSize: 24,
              },
              YdlKsliGP5: {
                type: 'shape',
                xywh: '[2745.0714148844436,-1664.712207988944,460.09024318240836,179]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0.1,
                filled: false,
                fillColor: '--affine-palette-transparent',
                strokeWidth: 12,
                strokeColor: '--affine-palette-line-black',
                strokeStyle: 'solid',
                roughness: 1.4,
                id: 'YdlKsliGP5',
                index: 'b0B',
                seed: 258050253,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Category',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:BebasNeue',
                fontSize: 64,
                fontWeight: '400',
                fontStyle: 'normal',
              },
              nbjJoH4wrM: {
                type: 'shape',
                xywh: '[2337.235032734267,-1266.555301609645,460.09024318240836,179]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0.1,
                filled: false,
                fillColor: '--affine-palette-transparent',
                strokeWidth: 12,
                strokeColor: '--affine-palette-line-black',
                strokeStyle: 'dash',
                roughness: 1.4,
                id: 'nbjJoH4wrM',
                index: 'b0C',
                seed: 7375873,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Item 2',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:BebasNeue',
                fontSize: 64,
                fontWeight: '400',
                fontStyle: 'normal',
              },
              YtuZAnHUYB: {
                type: 'shape',
                xywh: '[2476.3427975626896,-867.4460471408626,460.09024318240836,179]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0.1,
                filled: false,
                fillColor: '--affine-palette-transparent',
                strokeWidth: 12,
                strokeColor: '--affine-palette-line-black',
                strokeStyle: 'dash',
                roughness: 1.4,
                id: 'YtuZAnHUYB',
                index: 'b0D',
                seed: 479286311,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Item 1',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:BebasNeue',
                fontSize: 64,
                fontWeight: '400',
                fontStyle: 'normal',
              },
              'qFM-pXiKkU': {
                type: 'shape',
                xywh: '[2476.3427975626896,-189.2275382032975,460.09024318240836,179]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0.1,
                filled: false,
                fillColor: '--affine-palette-transparent',
                strokeWidth: 12,
                strokeColor: '--affine-palette-line-black',
                strokeStyle: 'dash',
                roughness: 1.4,
                id: 'qFM-pXiKkU',
                index: 'b0E',
                seed: 1454885780,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Item 1',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:BebasNeue',
                fontSize: 64,
                fontWeight: '400',
                fontStyle: 'normal',
              },
              qb1iqegVEn: {
                type: 'shape',
                xywh: '[2337.235032734267,209.88171626548535,460.09024318240836,179]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0.1,
                filled: false,
                fillColor: '--affine-palette-transparent',
                strokeWidth: 12,
                strokeColor: '--affine-palette-line-black',
                strokeStyle: 'dash',
                roughness: 1.4,
                id: 'qb1iqegVEn',
                index: 'b0F',
                seed: 1364763702,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Item 2',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:BebasNeue',
                fontSize: 64,
                fontWeight: '400',
                fontStyle: 'normal',
              },
              nBy4pPggx8: {
                type: 'shape',
                xywh: '[2744.9794167620507,608.9909707342678,460.09024318240836,178.5278226189996]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0.1,
                filled: false,
                fillColor: '--affine-palette-transparent',
                strokeWidth: 12,
                strokeColor: '--affine-palette-line-black',
                strokeStyle: 'solid',
                roughness: 1.4,
                id: 'nBy4pPggx8',
                index: 'b0G',
                seed: 1901980653,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Category',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:BebasNeue',
                fontSize: 64,
                fontWeight: '400',
                fontStyle: 'normal',
              },
              WxGdPLFF7I: {
                type: 'connector',
                mode: 0,
                strokeWidth: 12,
                stroke: '--affine-palette-line-black',
                strokeStyle: 'solid',
                roughness: 1.4,
                source: {
                  id: 'YdlKsliGP5',
                  position: [0.5, 1],
                },
                target: {
                  id: '59EeImMqdn',
                  position: [0.5, 0],
                },
                id: 'WxGdPLFF7I',
                index: 'b0H',
                seed: 1206651599,
                rearEndpointStyle: 'Triangle',
              },
              '9Vma3UWnNr': {
                type: 'connector',
                mode: 0,
                strokeWidth: 12,
                stroke: '--affine-palette-line-black',
                strokeStyle: 'solid',
                roughness: 1.4,
                source: {
                  id: 'nBy4pPggx8',
                  position: [0.5, 0],
                },
                target: {
                  id: '59EeImMqdn',
                  position: [0.5, 1],
                },
                id: '9Vma3UWnNr',
                index: 'b0I',
                seed: 177558392,
                rearEndpointStyle: 'Triangle',
              },
              '8G_qz8m8ZR': {
                type: 'connector',
                mode: 0,
                strokeWidth: 12,
                stroke: '--affine-palette-line-black',
                strokeStyle: 'dash',
                roughness: 1.4,
                source: {
                  id: 'nbjJoH4wrM',
                  position: [1, 0.5],
                },
                target: {
                  position: [3070.6691451446763, -1179.3735758624252],
                },
                rearEndpointStyle: 'None',
                id: '8G_qz8m8ZR',
                index: 'b0J',
                seed: 1119718175,
                xywh: '[2797.3252759166753,-1179.3735758624252,273.3438692279992,2.318274252779929]',
              },
              gAWn5CJzB0: {
                type: 'connector',
                mode: 0,
                strokeWidth: 12,
                stroke: '--affine-palette-line-black',
                strokeStyle: 'dash',
                roughness: 1.4,
                source: {
                  id: 'YtuZAnHUYB',
                  position: [1, 0.5],
                },
                target: {
                  position: [3197.167794805597, -777.7393530478231],
                },
                rearEndpointStyle: 'None',
                id: 'gAWn5CJzB0',
                index: 'b0K',
                seed: 681420993,
                xywh: '[2936.433040745098,-777.9460471408626,260.7347540604974,1]',
              },
              y6M55mpu2c: {
                type: 'connector',
                mode: 0,
                strokeWidth: 12,
                stroke: '--affine-palette-line-black',
                strokeStyle: 'dash',
                roughness: 1.4,
                source: {
                  id: 'qFM-pXiKkU',
                  position: [1, 0.5],
                },
                target: {
                  position: [3196.6796597574144, -100.3127946918575],
                },
                id: 'y6M55mpu2c',
                index: 'b0L',
                seed: 1199698523,
                rearEndpointStyle: 'None',
                xywh: '[2936.433040745098,-100.3127946918575,260.24661901231457,1]',
              },
              YGawkS_Y_A: {
                type: 'connector',
                mode: 0,
                strokeWidth: 12,
                stroke: '--affine-palette-line-black',
                strokeStyle: 'dash',
                roughness: 1.4,
                source: {
                  id: 'qb1iqegVEn',
                  position: [1, 0.5],
                },
                target: {
                  position: [3071.1605587073877, 297.85112944355745],
                },
                rearEndpointStyle: 'None',
                id: 'YGawkS_Y_A',
                index: 'b0M',
                seed: 1767875084,
                xywh: '[2797.3252759166753,297.85112944355745,273.8352827907106,1.5305868219278977]',
              },
              mjeZl1OzPP: {
                type: 'group',
                children: {
                  'affine:surface:ymap': true,
                  json: {
                    '59EeImMqdn': true,
                    YdlKsliGP5: true,
                    nbjJoH4wrM: true,
                    YtuZAnHUYB: true,
                    'qFM-pXiKkU': true,
                    qb1iqegVEn: true,
                    nBy4pPggx8: true,
                    WxGdPLFF7I: true,
                    '9Vma3UWnNr': true,
                    '8G_qz8m8ZR': true,
                    gAWn5CJzB0: true,
                    y6M55mpu2c: true,
                    YGawkS_Y_A: true,
                  },
                },
                title: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Group 1',
                    },
                  ],
                },
                id: 'mjeZl1OzPP',
                index: 'b0N',
                seed: 36810841,
                xywh: '[4283.359303793482,-1843.3680295990064,1606.5891618532305,2452.7111720506955]',
              },
              QGw56v5i0o: {
                type: 'shape',
                xywh: '[-380.54233706280814,-473.3367926720805,478.63157673821706,69]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0,
                filled: true,
                fillColor: '--affine-palette-shape-black',
                strokeWidth: 4,
                strokeColor: '--affine-palette-line-yellow',
                strokeStyle: 'none',
                roughness: 1.4,
                id: 'QGw56v5i0o',
                index: 'b0P',
                seed: 2120642858,
                color: '--affine-palette-line-white',
                text: {
                  'affine:surface:text': true,
                  delta: [],
                },
                fontFamily: 'blocksuite:surface:Inter',
                fontSize: 24,
              },
              NhzX8Xbk_k: {
                type: 'group',
                children: {
                  'affine:surface:ymap': true,
                  json: {
                    QGw56v5i0o: true,
                    'block:wvMZnrTQq6': true,
                  },
                },
                title: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Group 4',
                    },
                  ],
                },
                id: 'NhzX8Xbk_k',
                index: 'b0S',
                seed: 302778940,
              },
              u73K0TMRGA: {
                type: 'text',
                xywh: '[-2799.7807523400493,-1427.1178016096458,645.7605259166694,510]',
                rotate: 0,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert:
                        'A Fishbone template, also known as an Ishikawa diagram template, is a layout for identifying and categorizing potential causes of a problem. \n\nIt\'s structured with a central "problem" line and branches for different cause categories, aiding in systematic analysis.',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontSize: 36,
                fontFamily: 'blocksuite:surface:Poppins',
                fontWeight: '600',
                fontStyle: 'normal',
                textAlign: 'left',
                id: 'u73K0TMRGA',
                index: 'b0T',
                seed: 12448510,
                hasMaxWidth: true,
              },
              iq9QWCgsaZ: {
                type: 'text',
                xywh: '[-2799.7807523400493,-1550.3251705964055,294.9119873046875,89]',
                rotate: 0,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Fishbone',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontSize: 64,
                fontFamily: 'blocksuite:surface:Poppins',
                fontWeight: '600',
                fontStyle: 'normal',
                textAlign: 'left',
                id: 'iq9QWCgsaZ',
                index: 'b0U',
                seed: 730907506,
              },
              'y6nVBN-KBD': {
                type: 'group',
                children: {
                  'affine:surface:ymap': true,
                  json: {
                    u73K0TMRGA: true,
                    iq9QWCgsaZ: true,
                    'block:gBPwCn5J1q': true,
                  },
                },
                title: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Group 5',
                    },
                  ],
                },
                id: 'y6nVBN-KBD',
                index: 'b0V',
                seed: 417955431,
              },
            },
          },
          children: [
            {
              type: 'block',
              id: 'block:wvMZnrTQq6',
              flavour: 'affine:image',
              props: {
                caption: '',
                sourceId: 'YUo3S6WvBWTO3fcRR1iUKLXVFxnILmP-VTwdM3ai-h0=',
                width: 360,
                height: 544,
                index: 'b0R',
                xywh: '[-1110.587168532816,-1154.118895188299,834.0954657964721,1260.410926092447]',
                rotate: 0,
                size: 7354,
              },
              children: [],
            },
            {
              type: 'block',
              id: 'block:YsLXb-iBST',
              flavour: 'affine:image',
              props: {
                caption: '',
                sourceId: 'lrxxmLPiDeoDlEDUuBQp51JXetfPiG7l7HUzuKzDKuo=',
                width: 518,
                height: 592,
                index: 'b0Q',
                xywh: '[3589.6695762617496,-1124.648620104735,1200.170698007146,1371.6236548653098]',
                rotate: 0,
                size: 10015,
              },
              children: [],
            },
          ],
        },
        {
          type: 'block',
          id: 'block:gBPwCn5J1q',
          flavour: 'affine:note',
          props: {
            xywh: '[-2861.9332343849437,-1621.274707988944,756.8380038322657,787.9602056072466]',
            background: '--affine-background-secondary-color',
            index: 'b0SV',
            hidden: false,
            edgeless: {
              style: {
                borderRadius: 8,
                borderSize: 4,
                borderStyle: 'none',
                shadowType: '--affine-note-shadow-film',
              },
              collapse: true,
            },
          },
          children: [
            {
              type: 'block',
              id: 'block:5PXBeBglzC',
              flavour: 'affine:paragraph',
              props: {
                type: 'text',
                text: {
                  '$blocksuite:internal:text$': true,
                  delta: [],
                },
              },
              children: [],
            },
          ],
        },
      ],
    },
  },
};
