export default {
  name: 'Flow chart',
  preview: 'https://cdn.affine.pro/templates/cover/flow-chart.png',
  type: 'template',
  content: {
    type: 'page',
    meta: {
      id: 'page:home',
      title: '',
      createDate: 1702017557277,
      tags: [],
    },
    blocks: {
      type: 'block',
      id: 'block:PY8poNCR8Y',
      flavour: 'affine:page',
      props: {
        title: {
          '$blocksuite:internal:text$': true,
          delta: [],
        },
      },
      children: [
        {
          type: 'block',
          id: 'block:WDieoRBX9E',
          flavour: 'affine:surface',
          props: {
            elements: {
              'Ksae9QCWs-': {
                type: 'shape',
                xywh: '[-247.47478205709092,-248.0388645045369,304.01012629967965,155.86872626208762]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0.1,
                filled: true,
                fillColor: '--affine-palette-shape-blue',
                strokeWidth: 4,
                strokeColor: '--affine-palette-transparent',
                strokeStyle: 'none',
                roughness: 1.4,
                id: 'Ksae9QCWs-',
                index: 'a0',
                seed: 1302801432,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Action',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:Inter',
                fontWeight: '600',
                fontStyle: 'normal',
              },
              grsNaVQSdr: {
                type: 'shape',
                xywh: '[-212.31975120022017,-583.6962731429549,233.70006458593815,233.70006458593818]',
                rotate: 0,
                shapeType: 'ellipse',
                shapeStyle: 'General',
                radius: 0,
                filled: true,
                fillColor: '--affine-palette-shape-purple',
                strokeWidth: 4,
                strokeColor: '--affine-palette-line-yellow',
                strokeStyle: 'none',
                roughness: 1.4,
                id: 'grsNaVQSdr',
                index: 'a1',
                seed: 932975567,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Start',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:Inter',
                fontWeight: '600',
                fontStyle: 'normal',
              },
              ydD2xQblFu: {
                type: 'shape',
                xywh: '[409.12046501340956,236.5476392556416,217.73314401131432,218]',
                rotate: 0,
                shapeType: 'diamond',
                shapeStyle: 'General',
                radius: 0,
                filled: true,
                fillColor: '--affine-palette-shape-yellow',
                strokeWidth: 4,
                strokeColor: '--affine-palette-transparent',
                strokeStyle: 'none',
                roughness: 1.4,
                id: 'ydD2xQblFu',
                index: 'a2',
                seed: 1937946925,
                color: '--affine-palette-line-black',
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Yes\nor\nNo',
                    },
                  ],
                },
                fontFamily: 'blocksuite:surface:Inter',
                fontWeight: '600',
                fontStyle: 'normal',
              },
              'lfUx8CQ-vY': {
                type: 'shape',
                xywh: '[-247.47506314983983,9.787205810030432,304.01012629967965,155.86872626208762]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0.1,
                filled: true,
                fillColor: '--affine-palette-shape-blue',
                strokeWidth: 4,
                strokeColor: '--affine-palette-transparent',
                strokeStyle: 'none',
                roughness: 1.4,
                id: 'lfUx8CQ-vY',
                index: 'a3',
                seed: 34577438,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Action',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:Inter',
                fontWeight: '600',
                fontStyle: 'normal',
              },
              HA3P0gQLSB: {
                type: 'shape',
                xywh: '[-246.63099698203268,267.19942246734837,304.01012629967965,156]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0.1,
                filled: true,
                fillColor: '--affine-palette-shape-blue',
                strokeWidth: 4,
                strokeColor: '--affine-palette-transparent',
                strokeStyle: 'none',
                roughness: 1.4,
                id: 'HA3P0gQLSB',
                index: 'a4',
                seed: 991259797,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Action',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:Inter',
                fontWeight: '600',
                fontStyle: 'normal',
              },
              '_PzH-12vky': {
                type: 'shape',
                xywh: '[-1523.3854715805187,606.7443200687947,304.01012629967965,155.86872626208762]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0.1,
                filled: true,
                fillColor: '--affine-palette-shape-blue',
                strokeWidth: 4,
                strokeColor: '--affine-palette-transparent',
                strokeStyle: 'none',
                roughness: 1.4,
                id: '_PzH-12vky',
                index: 'a5',
                seed: 2045093249,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Action',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:Inter',
                fontWeight: '600',
                fontStyle: 'normal',
              },
              EUdfqi0sLy: {
                type: 'shape',
                xywh: '[-1116.510445120214,575.6786831998384,217.73314401131432,218]',
                rotate: 0,
                shapeType: 'diamond',
                shapeStyle: 'General',
                radius: 0,
                filled: true,
                fillColor: '--affine-palette-shape-yellow',
                strokeWidth: 4,
                strokeColor: '--affine-palette-transparent',
                strokeStyle: 'none',
                roughness: 1.4,
                id: 'EUdfqi0sLy',
                index: 'a6',
                seed: 257218715,
                color: '--affine-palette-line-black',
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Yes\nor\nNo',
                    },
                  ],
                },
                fontFamily: 'blocksuite:surface:Inter',
                fontWeight: '600',
                fontStyle: 'normal',
              },
              h37vuXQ2Bk: {
                type: 'shape',
                xywh: '[365.9819738692269,-68.1443631310438,304.01012629967965,155.86872626208762]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0.1,
                filled: true,
                fillColor: '--affine-palette-shape-blue',
                strokeWidth: 4,
                strokeColor: '--affine-palette-transparent',
                strokeStyle: 'none',
                roughness: 1.4,
                id: 'h37vuXQ2Bk',
                index: 'a7',
                seed: 1474556994,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Action',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:Inter',
                fontWeight: '600',
                fontStyle: 'normal',
              },
              '3TVdFL78JJ': {
                type: 'shape',
                xywh: '[1041.1352410318743,267.61327612459775,304.01012629967965,155.86872626208762]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0.1,
                filled: true,
                fillColor: '--affine-palette-shape-blue',
                strokeWidth: 4,
                strokeColor: '--affine-palette-transparent',
                strokeStyle: 'none',
                roughness: 1.4,
                id: '3TVdFL78JJ',
                index: 'a8',
                seed: 1352046864,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Action',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:Inter',
                fontWeight: '600',
                fontStyle: 'normal',
              },
              h0EbkORWel: {
                type: 'connector',
                mode: 1,
                strokeWidth: 4,
                stroke: '--affine-palette-line-grey',
                strokeStyle: 'solid',
                roughness: 1.4,
                source: {
                  id: 'grsNaVQSdr',
                  position: [0.5, 1],
                },
                target: {
                  id: 'Ksae9QCWs-',
                  position: [0.5, 0],
                },
                id: 'h0EbkORWel',
                index: 'a9',
                seed: 612591943,
              },
              jWUjLqeUhv: {
                type: 'connector',
                mode: 1,
                strokeWidth: 2,
                stroke: '--affine-palette-transparent',
                strokeStyle: 'solid',
                roughness: 1.4,
                source: {
                  id: 'Ksae9QCWs-',
                  position: [0.5, 1],
                },
                target: {
                  id: 'lfUx8CQ-vY',
                  position: [0.5, 0],
                },
                id: 'jWUjLqeUhv',
                index: 'aA',
                seed: 1495329882,
              },
              g9HaseUVqV: {
                type: 'connector',
                mode: 1,
                strokeWidth: 2,
                stroke: '--affine-palette-transparent',
                strokeStyle: 'solid',
                roughness: 1.4,
                source: {
                  id: 'Ksae9QCWs-',
                  position: [0.5, 1],
                },
                target: {
                  id: 'lfUx8CQ-vY',
                  position: [0.5, 0],
                },
                id: 'g9HaseUVqV',
                index: 'aB',
                seed: 1303540064,
              },
              '5cBOgtqmw2': {
                type: 'connector',
                mode: 1,
                strokeWidth: 2,
                stroke: '--affine-palette-transparent',
                strokeStyle: 'solid',
                roughness: 1.4,
                source: {
                  id: 'Ksae9QCWs-',
                  position: [0.5, 1],
                },
                target: {
                  id: 'lfUx8CQ-vY',
                  position: [0.5, 0],
                },
                id: '5cBOgtqmw2',
                index: 'aC',
                seed: 1700867555,
              },
              '73uORSwPtw': {
                type: 'connector',
                mode: 1,
                strokeWidth: 2,
                stroke: '--affine-palette-transparent',
                strokeStyle: 'solid',
                roughness: 1.4,
                source: {
                  id: 'Ksae9QCWs-',
                  position: [0.5, 1],
                },
                target: {
                  position: [-70.03439413300964, -28.99846627782921],
                },
                id: '73uORSwPtw',
                index: 'aD',
                seed: 1958199736,
              },
              'Dc-8C3utva': {
                type: 'connector',
                mode: 1,
                strokeWidth: 4,
                stroke: '--affine-palette-line-grey',
                strokeStyle: 'solid',
                roughness: 1.4,
                source: {
                  id: 'Ksae9QCWs-',
                  position: [0.5, 1],
                },
                target: {
                  id: 'lfUx8CQ-vY',
                },
                id: 'Dc-8C3utva',
                index: 'aE',
                seed: 2045084674,
              },
              pkwHC7_RuX: {
                type: 'connector',
                mode: 1,
                strokeWidth: 4,
                stroke: '--affine-palette-line-grey',
                strokeStyle: 'solid',
                roughness: 1.4,
                source: {
                  id: 'lfUx8CQ-vY',
                  position: [0.5, 1],
                },
                target: {
                  id: 'HA3P0gQLSB',
                },
                id: 'pkwHC7_RuX',
                index: 'aF',
                seed: 1320381362,
              },
              '2Vwl_h4K_8': {
                type: 'connector',
                mode: 1,
                strokeWidth: 4,
                stroke: '--affine-palette-line-grey',
                strokeStyle: 'solid',
                roughness: 1.4,
                source: {
                  id: 'HA3P0gQLSB',
                  position: [1, 0.5],
                },
                target: {
                  id: 'ydD2xQblFu',
                  position: [0, 0.4999999999999999],
                },
                id: '2Vwl_h4K_8',
                index: 'aG',
                seed: 655809891,
              },
              RbBZTZ2H2f: {
                type: 'connector',
                mode: 1,
                strokeWidth: 4,
                stroke: '--affine-palette-line-grey',
                strokeStyle: 'solid',
                roughness: 1.4,
                source: {
                  id: 'ydD2xQblFu',
                  position: [0.5, 0],
                },
                target: {
                  id: 'h37vuXQ2Bk',
                },
                id: 'RbBZTZ2H2f',
                index: 'aH',
                seed: 1830139278,
              },
              hAUiGDCwni: {
                type: 'connector',
                mode: 1,
                strokeWidth: 4,
                stroke: '--affine-palette-line-grey',
                strokeStyle: 'solid',
                roughness: 1.4,
                source: {
                  id: 'h37vuXQ2Bk',
                  position: [1, 0.5],
                },
                target: {
                  id: '3TVdFL78JJ',
                  position: [0.49999999999999983, 0],
                },
                id: 'hAUiGDCwni',
                index: 'aK',
                seed: 602366653,
              },
              gUu2DraEHc: {
                type: 'text',
                xywh: '[525.5525784058001,151.41,41.88067626953125,28.5]',
                rotate: 0,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Yes',
                    },
                  ],
                },
                color: '--affine-palette-line-grey',
                fontSize: 24,
                fontFamily: 'blocksuite:surface:Inter',
                fontWeight: '600',
                fontStyle: 'normal',
                textAlign: 'left',
                id: 'gUu2DraEHc',
                index: 'aM',
                seed: 868124845,
              },
              YHgu7oxCyx: {
                type: 'connector',
                mode: 1,
                strokeWidth: 4,
                stroke: '--affine-palette-line-grey',
                strokeStyle: 'solid',
                roughness: 1.4,
                source: {
                  id: 'ydD2xQblFu',
                  position: [1, 0.5],
                },
                target: {
                  id: '3TVdFL78JJ',
                  position: [0, 0.5000000000000001],
                },
                id: 'YHgu7oxCyx',
                index: 'aN',
                seed: 1866232091,
              },
              n5Ep0HkOKR: {
                type: 'text',
                xywh: '[795.8080465225494,310.0815517259986,33,29]',
                rotate: 0,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'No',
                    },
                  ],
                },
                color: '--affine-palette-line-grey',
                fontSize: 24,
                fontFamily: 'blocksuite:surface:Inter',
                fontWeight: '600',
                fontStyle: 'normal',
                textAlign: 'left',
                id: 'n5Ep0HkOKR',
                index: 'aO',
                seed: 1709632114,
              },
              '03cE0Z-fxk': {
                type: 'shape',
                xywh: '[1084.273427994343,613.2702190136646,217.73314401131432,218]',
                rotate: 0,
                shapeType: 'diamond',
                shapeStyle: 'General',
                radius: 0,
                filled: true,
                fillColor: '--affine-palette-shape-yellow',
                strokeWidth: 4,
                strokeColor: '--affine-palette-transparent',
                strokeStyle: 'none',
                roughness: 1.4,
                id: '03cE0Z-fxk',
                index: 'aP',
                seed: 640115209,
                color: '--affine-palette-line-black',
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Yes\nor\nNo',
                    },
                  ],
                },
                fontFamily: 'blocksuite:surface:Inter',
                fontWeight: '600',
                fontStyle: 'normal',
              },
              'gZUhN-aYzi': {
                type: 'connector',
                mode: 1,
                strokeWidth: 4,
                stroke: '--affine-palette-line-grey',
                strokeStyle: 'solid',
                roughness: 1.4,
                source: {
                  id: '3TVdFL78JJ',
                  position: [0.5, 1],
                },
                target: {
                  id: '03cE0Z-fxk',
                  position: [0.5000000000000001, 0],
                },
                id: 'gZUhN-aYzi',
                index: 'aQ',
                seed: 968545969,
              },
              _QU7lLy0c0: {
                type: 'connector',
                mode: 1,
                strokeWidth: 4,
                stroke: '--affine-palette-line-grey',
                strokeStyle: 'solid',
                roughness: 1.4,
                source: {
                  id: '03cE0Z-fxk',
                  position: [0, 0.5],
                },
                target: {
                  id: 'ydD2xQblFu',
                  position: [0.5000000000000001, 0.9999999999999999],
                },
                id: '_QU7lLy0c0',
                index: 'aR',
                seed: 1414857367,
              },
              ZBppFGHIy0: {
                type: 'text',
                xywh: '[795.8080465225494,684.6786831998384,33,29]',
                rotate: 0,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'No',
                    },
                  ],
                },
                color: '--affine-palette-line-grey',
                fontSize: 24,
                fontFamily: 'blocksuite:surface:Inter',
                fontWeight: '600',
                fontStyle: 'normal',
                textAlign: 'left',
                id: 'ZBppFGHIy0',
                index: 'aS',
                seed: 69272275,
              },
              qvhoYUj230: {
                type: 'shape',
                xywh: '[365.98493685016024,1021.0556368689562,304.01012629967965,155.86872626208762]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0.1,
                filled: true,
                fillColor: '--affine-palette-shape-blue',
                strokeWidth: 4,
                strokeColor: '--affine-palette-transparent',
                strokeStyle: 'none',
                roughness: 1.4,
                id: 'qvhoYUj230',
                index: 'aT',
                seed: 1559703065,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Action',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:Inter',
                fontWeight: '600',
                fontStyle: 'normal',
              },
              xixP2sNR_L: {
                type: 'connector',
                mode: 1,
                strokeWidth: 4,
                stroke: '--affine-palette-line-grey',
                strokeStyle: 'solid',
                roughness: 1.4,
                source: {
                  id: '03cE0Z-fxk',
                  position: [0.5, 1],
                },
                target: {
                  id: 'qvhoYUj230',
                  position: [0.49999999999999983, 0],
                },
                id: 'xixP2sNR_L',
                index: 'aU',
                seed: 238268077,
              },
              POQhMd2xAx: {
                type: 'text',
                xywh: '[790.8080465225494,889.6284572778808,43,29]',
                rotate: 0,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Yes',
                    },
                  ],
                },
                color: '--affine-palette-line-grey',
                fontSize: 24,
                fontFamily: 'blocksuite:surface:Inter',
                fontWeight: '600',
                fontStyle: 'normal',
                textAlign: 'left',
                id: 'POQhMd2xAx',
                index: 'aV',
                seed: 1317364024,
              },
              R38499YZHD: {
                type: 'shape',
                xywh: '[-372.3894009393302,989.9927987716874,217.73314401131432,218]',
                rotate: 0,
                shapeType: 'diamond',
                shapeStyle: 'General',
                radius: 0,
                filled: true,
                fillColor: '--affine-palette-shape-yellow',
                strokeWidth: 4,
                strokeColor: '--affine-palette-transparent',
                strokeStyle: 'none',
                roughness: 1.4,
                id: 'R38499YZHD',
                index: 'aW',
                seed: 1967354475,
                color: '--affine-palette-line-black',
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Yes\nor\nNo',
                    },
                  ],
                },
                fontFamily: 'blocksuite:surface:Inter',
                fontWeight: '600',
                fontStyle: 'normal',
              },
              LKkTnFuF4B: {
                type: 'connector',
                mode: 1,
                strokeWidth: 4,
                stroke: '--affine-palette-line-grey',
                strokeStyle: 'solid',
                roughness: 1.4,
                source: {
                  id: 'qvhoYUj230',
                  position: [0, 0.5],
                },
                target: {
                  id: 'R38499YZHD',
                  position: [0.9999999999999998, 0.5],
                },
                id: 'LKkTnFuF4B',
                index: 'aX',
                seed: 559788331,
                frontEndpointStyle: 'None',
                rearEndpointStyle: 'Arrow',
              },
              sI0UgSQbhJ: {
                type: 'shape',
                xywh: '[-415.5278920835129,1423.646193915283,304.01012629967965,155.86872626208762]',
                rotate: 0,
                shapeType: 'rect',
                shapeStyle: 'General',
                radius: 0.1,
                filled: true,
                fillColor: '--affine-palette-shape-blue',
                strokeWidth: 4,
                strokeColor: '--affine-palette-transparent',
                strokeStyle: 'none',
                roughness: 1.4,
                id: 'sI0UgSQbhJ',
                index: 'aY',
                seed: 686892262,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Action',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:Inter',
                fontWeight: '600',
                fontStyle: 'normal',
              },
              u46zCKWJW1: {
                type: 'connector',
                mode: 1,
                strokeWidth: 4,
                stroke: '--affine-palette-line-grey',
                strokeStyle: 'solid',
                roughness: 1.4,
                source: {
                  id: 'R38499YZHD',
                  position: [0.5, 1],
                },
                target: {
                  id: 'sI0UgSQbhJ',
                  position: [0.5000000000000002, 0],
                },
                id: 'u46zCKWJW1',
                index: 'aZ',
                seed: 241091117,
              },
              '3WulwKaXKS': {
                type: 'shape',
                xywh: '[-380.370032292969,1726.9003834176424,233.70006458593815,234]',
                rotate: 0,
                shapeType: 'ellipse',
                shapeStyle: 'General',
                radius: 0,
                filled: true,
                fillColor: '--affine-palette-shape-purple',
                strokeWidth: 4,
                strokeColor: '--affine-palette-line-yellow',
                strokeStyle: 'none',
                roughness: 1.4,
                id: '3WulwKaXKS',
                index: 'aa',
                seed: 1936488363,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Result',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontFamily: 'blocksuite:surface:Inter',
                fontWeight: '600',
                fontStyle: 'normal',
              },
              '7OY4PHXyk_': {
                type: 'connector',
                mode: 1,
                strokeWidth: 4,
                stroke: '--affine-palette-line-grey',
                strokeStyle: 'solid',
                roughness: 1.4,
                source: {
                  id: 'sI0UgSQbhJ',
                  position: [0.5, 1],
                },
                target: {
                  id: '3WulwKaXKS',
                  position: [0.5000000000000001, 0],
                },
                id: '7OY4PHXyk_',
                index: 'ab',
                seed: 1390346335,
                xywh: '[-263.52282893367305,1638.011671002082,1,212.18000000000006]',
              },
              rwfhtkmxGV: {
                type: 'text',
                xywh: '[-247.48,1301.3200000000002,33,29]',
                rotate: 0,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'No',
                    },
                  ],
                },
                color: '--affine-palette-line-grey',
                fontSize: 24,
                fontFamily: 'blocksuite:surface:Inter',
                fontWeight: '600',
                fontStyle: 'normal',
                textAlign: 'left',
                id: 'rwfhtkmxGV',
                index: 'ac',
                seed: 670777356,
              },
              dwbykFhJKm: {
                type: 'connector',
                mode: 1,
                strokeWidth: 4,
                stroke: '--affine-palette-line-grey',
                strokeStyle: 'solid',
                roughness: 1.4,
                source: {
                  id: 'R38499YZHD',
                  position: [0, 0.5],
                },
                target: {
                  id: 'lfUx8CQ-vY',
                  position: [0, 0.5],
                },
                id: 'dwbykFhJKm',
                index: 'ad',
                seed: 1423832944,
              },
              fEBd99ZiQN: {
                type: 'text',
                xywh: '[-377.54477971118376,584.77,41.88067626953125,28.5]',
                rotate: 0,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Yes',
                    },
                  ],
                },
                color: '--affine-palette-line-grey',
                fontSize: 24,
                fontFamily: 'blocksuite:surface:Inter',
                fontWeight: '600',
                fontStyle: 'normal',
                textAlign: 'left',
                id: 'fEBd99ZiQN',
                index: 'ae',
                seed: 1273423653,
              },
              'GOXMT-TQ6R': {
                type: 'text',
                xywh: '[-1552.638047141807,-89.43413110013387,707,353]',
                rotate: 0,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert:
                        'A Flowchart template is a diagrammatic tool used to visually represent a process or workflow. \n\nIt typically consists of various shapes like rectangles, diamonds, and arrows that denote steps, decisions, and the flow direction, helping to map out and understand complex processes systematically.\n\nPress “S” to quickly place shapes onto the canvas. Other shapes can be selected from the toolbar or swapped from the shape menu.\n\nPress "C" to quickly select the Connector tool. You can draw magnetic between objects on the canvas. The blue handles will let you adjust their exact path.\n\n',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontSize: 20,
                fontFamily: 'blocksuite:surface:Inter',
                fontWeight: '600',
                fontStyle: 'normal',
                textAlign: 'left',
                id: 'GOXMT-TQ6R',
                index: 'af',
                seed: 2081052614,
                hasMaxWidth: true,
              },
              AO_Fu_3p0U: {
                type: 'text',
                xywh: '[-1552.638047141807,-208.46965582048261,309.5908508300781,76.5]',
                rotate: 0,
                text: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Flowchart',
                    },
                  ],
                },
                color: '--affine-palette-line-black',
                fontSize: 64,
                fontFamily: 'blocksuite:surface:Inter',
                fontWeight: '600',
                fontStyle: 'normal',
                textAlign: 'left',
                id: 'AO_Fu_3p0U',
                index: 'ah',
                seed: 1348985286,
              },
              a3b3faEw3S: {
                type: 'group',
                children: {
                  'affine:surface:ymap': true,
                  json: {
                    'GOXMT-TQ6R': true,
                    AO_Fu_3p0U: true,
                    'block:ofacia51GI': true,
                  },
                },
                title: {
                  'affine:surface:text': true,
                  delta: [
                    {
                      insert: 'Group 1',
                    },
                  ],
                },
                id: 'a3b3faEw3S',
                index: 'ai',
                seed: 1665064781,
              },
            },
          },
          children: [
            {
              type: 'block',
              id: 'block:CUbp6bMsMM',
              flavour: 'affine:frame',
              props: {
                title: {
                  '$blocksuite:internal:text$': true,
                  delta: [
                    {
                      insert: 'Key',
                    },
                  ],
                },
                background: '--affine-palette-transparent',
                xywh: '[-1593.9377813099973,506.20729872115555,811.2479982635791,333.36808035828614]',
                index: 'a0',
              },
              children: [],
            },
          ],
        },
        {
          type: 'block',
          id: 'block:ofacia51GI',
          flavour: 'affine:note',
          props: {
            xywh: '[-1593.9377813099973,-253.99866559224466,780.8156813417015,541.4276639514948]',
            background: '--affine-background-secondary-color',
            index: 'Zz',
            hidden: false,
            edgeless: {
              style: {
                borderRadius: 8,
                borderSize: 4,
                borderStyle: 'none',
                shadowType: '--affine-note-shadow-film',
              },
              collapse: true,
            },
          },
          children: [
            {
              type: 'block',
              id: 'block:S2XRRZ9QZa',
              flavour: 'affine:paragraph',
              props: {
                type: 'text',
                text: {
                  '$blocksuite:internal:text$': true,
                  delta: [],
                },
              },
              children: [],
            },
          ],
        },
      ],
    },
  },
};
