#!/bin/bash

# Cleanup nightly version tags generated by changsets
git push origin --delete $(git tag -l | grep "\-[a-f0-9]\{7\}$")
# git push origin --delete $(git tag -l | grep -E "blocksuite\/store|blocksuite\/blocks|blocksuite\/react")
