name: Add issues and pull requests to AFFiNE Kanban

on:
  issues:
    types:
      - opened
      - transferred
      - labeled
  pull_request:
    types:
      - opened
      - labeled

jobs:
  add-to-project:
    name: Add issues and pull requests to GitHub project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@0.4.0
        with:
          # You can target a repository in a different organization
          # to the issue
          project-url: https://github.com/orgs/toeverything/projects/10
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          # labeled: bug, needs-triage
          # label-operator: OR
