name: Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.husky'
      - '.vscode'
      - '**.md'
      - 'scripts/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.husky'
      - '.vscode'
      - '**.md'
      - 'scripts/**'

jobs:
  build-next:
    name: Build Next.js Example
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.9.5
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Next.js Example
        run: pnpm run build
        working-directory: packages/react/examples/next
