name: Browser compatibility (comment trigger)

on:
  issue_comment:
    types: [created]

jobs:
  trigger:
    runs-on: ubuntu-latest
    if: github.repository == 'toeverything/blocksuite' && github.event.issue.pull_request && startsWith(github.event.comment.body, '/tier1')
    steps:
      - uses: actions/github-script@v6
        id: reaction
        with:
          script: |
            const user = context.payload.sender.login
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: 'rocket',
            })

      - uses: actions/github-script@v6
        id: get-pr-data
        with:
          script: |
            console.log(`Get PR info: ${context.repo.owner}/${context.repo.repo}#${context.issue.number}`)
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
            return {
              repoName: pr.head.repo.full_name,
              ref: pr.head.ref
            }

      - uses: actions/github-script@v6
        id: trigger
        with:
          script: |
            const prData = ${{ steps.get-pr-data.outputs.result }}
            console.log(`Run /tier1, repo: ${prData.repoName} ref: ${prData.ref}`)
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'browser-compatibility.yml',
              ref: 'main',
              inputs: {
                repo: prData.repoName,
                ref: prData.ref,
              }
            })
