name: Label Checker
on:
  merge_group:
  pull_request:
    types:
      - labeled
      - unlabeled

jobs:
  check_labels:
    name: PR should not have a blocked label
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          none_of: blocked
          repo_token: ${{ secrets.GITHUB_TOKEN }}
