name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.9.5
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run prettier
        run: npx prettier --cache --check packages tests

      - name: Run ESLint
        # by default: eslint will save the cache files on cwd
        #   Refs: https://eslint.org/docs/latest/user-guide/command-line-interface#--cache-location
        run: npx eslint --cache --cache-location=node_modules/.cache/.eslintcache/ ./ --max-warnings=0

      - uses: actions/cache@v3
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}
      - uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/packages/react/examples/next/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-
      - name: Run type check
        # run: pnpm exec tsc -b
        run: pnpm build
