name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run type check
        run: pnpm build:packages && pnpm build:playground
        env:
          NODE_OPTIONS: --max-old-space-size=16384

      - name: Run ESLint
        # ESLint will save the cache files on cwd by default,
        # so the lint command uses node_modules for caching.
        # Refs: https://eslint.org/docs/latest/user-guide/command-line-interface#--cache-location
        # By using eslint-plugin-prettier, eslint will lint the prettier rules as well.
        run: pnpm lint

      - name: Run lit-lint
        run: pnpm lit-lint

      - name: Run circular imports detect
        run: pnpm circular

      - uses: actions/cache@v3
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}
