name: PR Title Lint

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - master

permissions:
  contents: read

jobs:
  check-pull-request-title:
    name: Check pull request title
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - run: echo "${{ github.event.pull_request.title }}" | npx commitlint -g ./.commitlintrc.json
