name: Publish

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 7.9.5
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: PLAYWRIGHT_BROWSERS_PATH=0 npx playwright install chromium

      - name: Lint
        run: npm run lint -- --max-warnings=0

      - name: Run lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Run tests
        run: PLAYWRIGHT_BROWSERS_PATH=0 pnpm test -- --forbid-only

      - name: Publish
        run: pnpm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
